### ISSUE TITLE
Invalid search endpoint on blue collections button

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#1]
Seeing error "Your search could not be completed due to an unexpected error", when clicking on "COLLECTIONS" button on front page of library. The URL " http://archivesspace.cshl.edu/search" should be: "http://archivesspace.cshl.edu".

**Comment by tomadams** [comment]
We are redefining the Blue buttons, so this link might disappear from that area. Just a note to what the corrected endpoint is.

**Comment by srunkows** [comment]
I had a thought about the blue buttons on the landing page. You had said they were very, I can't remember the words you used, busy or bold or attention grabbing. 

I totally forgot, we also have a style for a ghost button which you may want to consider. They're less bold.  We use it on the Newsstand. Here's a screen capture so you can see if you might like the way it looks. The button is 'See all in the news'. Let me know what you think.

<img width="390" alt="Screen Shot 2020-08-13 at 2 34 57 PM" src="https://user-images.githubusercontent.com/69586159/90173233-254c7780-dd72-11ea-96a6-789ce86125e6.png">

**Comment by tomadams** [comment]
For the new lineup of blue buttons, which  include library's "Resources" and "Services", it is appropriate for it to be attention grabbing. Did not want that, when we initially had links to archives or center for humanities.

Good to know about the ghost button styling. Will keep it in mind.
