### ISSUE TITLE
Library Homepage - Secure to unsecure from search box

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#12]
I am getting the following warning in my browser:

> The information you have entered on this page will be sent over an insecure connection and could be read by a third party.
> Are you sure you want to send this information?

Can your place make sure that for: Journals, Books, LibGuides and Institutional Repository are all using https:// in their respective  search URL.

**Comment by srunkows** [comment]
All URLs now are using https, however, I still receive the 'insecure connection' message when searching Journals and the Repository. Books and LibGuide searches are good and generate 'your connection is secure' message.

**Comment by tomadams** [comment]
They are all looking good to me in Firefox. What browser are you using, are you still seeing the  'insecure connection' message?

**Comment by srunkows** [comment]
I'm using Chrome and still see the issue. Here's a screen capture of a journal search I just did from the Library landing page (https://lib-review-cshl-core.pantheonsite.io/library/) search box
<img width="1031" alt="Screen Shot 2020-08-13 at 2 24 31 PM" src="https://user-images.githubusercontent.com/69586159/90172241-b6225380-dd70-11ea-9728-7d3d59afa0c2.png">

**Comment by tomadams** [comment]
I will need to follow up on this. Reassigning it to me.

**Comment by tomadams** [comment]
The not secure message from the Journals tab was only occurring when the search string did not match in BrowZine and was forwarded to the SFX instance. Had vendor reassign the SFX to https URL. Appears to function correctly now.

The IR is still outstanding for me to work on.

**Comment by srunkows** [comment]
excellent. Just tested it and I no longer see the 'connection not secure' message.

**Comment by tomadams** [comment]
Good.
