### ISSUE TITLE
Library Homepage - Search Box - Website

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#13]
Right now I would prefer that the search request does not contain the library tag. This way a person is able to see the full list of search results.
If the list too long, they can always filter it with a tag.

**Comment by srunkows** [comment]
fixed, please review.

**Comment by tomadams** [comment]
Looks good.

**Comment by tomadams** [comment]
Mila would prefer to rename the tab in the library homepage search box from "Website", to "Library Website" (with a title from "Website search" to "Library Website Search"). She would like to have it only display both Library and Archives content.
I know you were looking into check boxes instead of radio buttons on the search field. Please let us know what you are able to do.

**Comment by srunkows** [comment]
This is done and ready for review.

Because the search currently only uses radio buttons, I can only pass 1 hidden value to the search engine. For now, I set it to Library. When I implement the checkboxes, I should be able to pass multiple hidden values to the search engine and return results for both Library & Archives instead of just Library.

**Comment by tomadams** [comment]
Understood. Will check if Mila is fine with it.

**Comment by tomadams** [comment]
With the new search filter checkbox enhancements, looks like adding a "Library Website Search" that includes both library and the archives will soon be a reality.

**Comment by srunkows** [comment]
> With the new search filter checkbox enhancements, looks like adding a "Library Website Search" that includes both library and the archives will soon be a reality.

It is now a reality. I just made the update to the search box on your landing page.

**Comment by tomadams** [comment]
Thanks. With the added bonus that memory board is the top listing. Outstanding.
