### ISSUE TITLE
Database & Protocol Page - Contents

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#15]
Need a descriptive summary, for this page.

Need to refresh contents. Should we limited our entries to CSHL Paid resources?

Nuclic Acid Research contains an up-to-date list of relevant databases at: http://www.oxfordjournals.org/nar/database/c/
I like the way it is broken down. 

Paper describing the DB collection:
https://academic.oup.com/nar/article/45/D1/D1/2770636

Might be a good project for Roxanne.

**Comment by srunkows** [comment]
Please review: https://lib-review-cshl-core.pantheonsite.io/library/resources/databases-protocols/

**Comment by tomadams** [comment]
The expanded "ALL" tab, should also include the protocol links at the bottom.

**Comment by srunkows** [comment]
This is done. Please review.

**Comment by tomadams** [comment]
When the "All" tab is selected, I do not see the Protocol URL listed at the bottom.

The Bibliographic Databases items, all seem to be shifted slightly to the right (compared to the other entries.)

**Comment by srunkows** [comment]
That's beyond bizarre. I must have made the update to the Live draft page instead of the lib-review branch published page. Anyway this should now be fixed. The reason the entries weren't lining up correctly is because Chris failed to put the starting and ending unordered list tag on the lists. I fixed the lists and they should all now display with the same indentation. Please review.

**Comment by tomadams** [comment]
Looks good.

**Comment by tomadams** [comment]
Based upon some feedback, I will need to design a few more images. Assigning this to Tom, (not for Sue  yet).
rm BIST and SciVal icons
Springer Nature icon to Springer Nature Experiments
add IOP Science iopsicence.iop.org/journalList
NCBI ncbi.nlm.mih.gov  but to databases all
Clarivate Analytics to Web of Science
Flower to have text.

**Comment by tomadams** [comment]
Added some links...
Based upon some feedback, I will need to design a few more images. Assigning this to Tom, (not for Sue  yet).
rm BIST and SciVal icons
Springer Nature icon to Springer Nature Experiments [https://experiments.springernature.com/](https://experiments.springernature.com/)
add IOP Science [https://iopscience.iop.org/journalList](https://iopscience.iop.org/journalList)
NCBI ncbi.nlm.mih.gov  but to [https://www.ncbi.nlm.nih.gov/guide/all/](https://www.ncbi.nlm.nih.gov/guide/all/)
Clarivate Analytics to Web of Science
Flower to have text.

**Comment by tomadams** [comment]
Just sent icon images via email.

The JoVE button should go to: [https://www.jove.com/](https://www.jove.com/)

**Comment by srunkows** [comment]
I started working on this. 

fyi, the images sent are a different aspect ratio than the existing icons so the new ones are taller. Which is fine if you plan on replacing all the existing ones with the new aspect ratio. See https://lib-review-cshl-core.pantheonsite.io/library/resources/databases-protocols/

**Comment by tomadams** [comment]
I just resent those images plus the IOP Science, in the original aspect ratio.

**Comment by srunkows** [comment]
I swapped out the new ones for the ones with a larger aspect ratio and added the IOP Science image. This is done and ready for review. Let me know if you want them ordered differently from how they currently are. Maybe alphabetically?

**Comment by tomadams** [comment]
Please add the links:
Springer Nature Experiments https://experiments.springernature.com/
IOP Science https://iopscience.iop.org/journalList
NIH https://www.ncbi.nlm.nih.gov/guide/all/
F100 https://f1000research.com/   (This might change.)

**Comment by srunkows** [comment]
Links have been added to the logo icons and is ready for review.

**Comment by tomadams** [comment]
As thought the, the link changed:
F1000 is now:  https://facultyopinions.com

**Comment by tomadams** [comment]
Don't change it yet, They also have a new ICON graphic. Change it once I send you the new graphic.

**Comment by tomadams** [comment]
Faculty Options looks good.

Change the following URL for Academic Search (Microsoft)  => https://academic.microsoft.com
Journal Citation Reports => http://jcr.clarivate.com/
remove: BISC eReference Directory
remove: CSHL Author Publications
Faculty 1000 is now => Faculty Opinions  https://facultyopinions.com
JSTOR => https://www.jstor.org/
PubMedCentral => https://www.ncbi.nlm.nih.gov/pmc/

**Comment by srunkows** [comment]
> Faculty Options looks good.
> 
> Change the following URL for Academic Search (Microsoft) => https://academic.microsoft.com
> Journal Citation Reports => http://jcr.clarivate.com/
> remove: BISC eReference Directory
> remove: CSHL Author Publications
> Faculty 1000 is now => Faculty Opinions https://facultyopinions.com
> JSTOR => https://www.jstor.org/
> PubMedCentral => https://www.ncbi.nlm.nih.gov/pmc/

These updates are done and ready for review.

**Comment by tomadams** [comment]
Great.
