### ISSUE TITLE
Library Resource - Page design

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#18]
Currently the page has a itemized list of links:

Journals
Databases
Protocols
E-Books
E-Books by Subject
Library Catalog
Magazine Rack
CSHL Institutional Repository
New Acquisitions
Library Wiki/Confluence
LibGuides
Copyright on eResources
Author Rights and Copyright

Would like to make the page more graphical, similar to the NYBG library.
![image](https://user-images.githubusercontent.com/1951133/90159183-0348fa00-dd5e-11ea-88d5-a0ae53285eb4.png)

The gallery order should be (first block should be first row):

Journals
Library Catalog
Databases & Protocols
E-Books

Institutional Repository
CSHL Theses
Faculty Profiles
Elements

LibGuides
Library Wiki
Magazine Rack

Will send some possible image suggestions via email. Ultimately might want to re-shoot with our own photos. Some of the other links might end up in the footer.

**Comment by srunkows** [comment]
I make a quick update to the page with one row boxes so you could get a feel for what it could look like. I used the logo as a place holder image for now, but it should give you enough of an idea of how it would look.

https://lib-review-cshl-core.pantheonsite.io/library/resources/

If you want me to continue to build out the other 2 rows after you review, I will.

The images should be at least 768px wide and will all need to be basically the same size or at least same aspect ratio so they are all uniform.

Let me know what you think and if you want me to build out the other 2 rows.

**Comment by tomadams** [comment]
I ended up sending you via email some images. They are 1:1 aspect ratio. Let's see how they look, If we wanted the images and captions together to be square, what size images would you need?

**Comment by srunkows** [comment]
Because the website is responsive, I'm not sure if we would be able to make a square for all screen sizes since it would change depending on screen size. The best would to just make sure they are all as uniform as possible. 

I'll get the other 2 rows built and images in today and send you a link when it's ready for your review.

**Comment by tomadams** [comment]
I want more buttons to be visible. I will re-crop the images to allow for that. Give me an hour.

**Comment by srunkows** [comment]
I need to know where the CSHL Theses and Elements buttons should point to.

Try a 16x9 ratio with the width being at least 768px

**Comment by tomadams** [comment]
Element needs to go to: https://elements.cshl.edu
Faculty Profiles needs to go to: https://facultyprofiles.cshl.edu/
We can remove "CSHL Theses".

**Comment by srunkows** [comment]
These updates are done and ready for review.

**Comment by tomadams** [comment]
Perfect.

**Comment by tomadams** [comment]
Please reorder the icons as follows. Please eliminate the restrictions of only 3 items in the second row.

Library Catalog
Journals
E-Books
Databases & Protocols
Institutional Repository
Faculty Profiles
Elements
LibGuides
Library Publications
Newspapers & Magazine Rack

**Comment by srunkows** [comment]
> Please reorder the icons as follows. Please eliminate the restrictions of only 3 items in the second row.
> 
> Library Catalog
> Journals
> E-Books
> Databases & Protocols
> Institutional Repository
> Faculty Profiles
> Elements
> LibGuides
> Library Publications
> Newspapers & Magazine Rack

This is done and ready for review, but I have a question. The last row has Library Wiki which is not in the above list. And now you have Library Publications. I'm not sure if you want me to delete Library Wiki and add Library Publications or just add Library Publications. And what image and link should be used for Publications?

**Comment by tomadams** [comment]
We want to rename "Library Wiki" and call it "Library Publications". So there will only be one. Same Wiki icon and same confluence URL.

**Comment by srunkows** [comment]
> We want to rename "Library Wiki" and call it "Library Publications". So there will only be one. Same Wiki icon and same confluence URL.

Thanks for the clarification. This is done and ready for review.

**Comment by tomadams** [comment]
Good.
