### ISSUE TITLE
Library Services

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#19]
Similar to the Library Resources page:
title and h1 Services =>  Library Services
Photo for buttons are emailed.

Buttons in the following order:

Interlibrary Loan
Getting Started
Remote Access
Library Help

Public Access Compliance
Data Management Planning
Science Informationists
Citation Software

Study Spaces
Meeting Rooms
Training Workshops
Online Training

Printing & Scanning
Thesis Binding
24-hour Self-Checkout

**Comment by srunkows** [comment]
I started working on this page, but I think I'm missing a few images, specifically:
printing & scanning
thesis binding
24-hr self checkout

Also, not sure where some of these boxes need to link to.

https://lib-review-cshl-core.pantheonsite.io/library/services/

**Comment by tomadams** [comment]
I just send you via email a few more images. Please add "3D Printing" after the "Printing & Scanning" button. Still owe you the "thesis binding" image.

The unlinked boxes will go to their own pages.

I was thinking that for those pages, the breadcrumb and h1 would go into the 2/3 column on the left and the same image that is used on the button, would go into a 1/3 column on the right. The text body of the page would be a full with column below.

**Comment by srunkows** [comment]
The templates for all pages have the H1 heading and breadcrumbs in full width rows and will not be changed. The content below these rows is where you can set up different column widths.

**Comment by tomadams** [comment]
Can we have the image in the top right of the main body of the text, with text wrapping around?

The tab section currently under all of the buttons, should be split into their individual pages, with the corresponding icon shown. The tabbed section should be eliminated, after they are copied to their individual pages.

**Comment by tomadams** [comment]
Text at Top:

Our science informationists and librarians are available to assist your research, whether you need to research a particular topic, obtain an article or book by interlibrary loan, make color copies, or use any of the other services listed below.

**Comment by tomadams** [comment]
The first button "Interlibrary Loan", should go to the "https://lib-review-cshl-core.pantheonsite.io/library/services/interlibrary-loan/", which is the existing ILL help page. However, we want to modify that page. The first tab "Interlibrary Loan (ILLiad)" material is to be moved to the top of the page, with the ILL image on the top right. The page name should be "Interlibrary Loan (ILLiad)"

The external link to ILLiad, needs to be made prominent, as a blue button.

The last 3 tabs (and their content) will appear at the bottom of the page.

The "Getting Started"  button on the services page, should be renamed "Orientation / Getting Started", this should point to it's own unique page and not the ILL help. (Content will follow.)

**Comment by tomadams** [comment]
Library Help image should go to about/contact

**Comment by tomadams** [comment]
Emailed thesis-binding graphic.

**Comment by srunkows** [comment]
> Can we have the image in the top right of the main body of the text, with text wrapping around?
> 
> The tab section currently under all of the buttons, should be split into their individual pages, with the corresponding icon shown. The tabbed section should be eliminated, after they are copied to their individual pages.

What do you want to do with the content in the first tab 'All' It's just a bulleted list of available services.  I've moved it up above the boxes with the new intro text but it may be redundant with the boxes.

**Comment by srunkows** [comment]
> The first button "Interlibrary Loan", should go to the "https://lib-review-cshl-core.pantheonsite.io/library/services/interlibrary-loan/", which is the existing ILL help page. However, we want to modify that page. The first tab "Interlibrary Loan (ILLiad)" material is to be moved to the top of the page, with the ILL image on the top right. The page name should be "Interlibrary Loan (ILLiad)"
> 
> The external link to ILLiad, needs to be made prominent, as a blue button.
> 
> The last 3 tabs (and their content) will appear at the bottom of the page.
> 
> The "Getting Started" button on the services page, should be renamed "Orientation / Getting Started", this should point to it's own unique page and not the ILL help. (Content will follow.)

These changes are done. Please review

**Comment by tomadams** [comment]
Liked the bulleted list of text move to the top of services. I will edit it down a little, when I get write access. In the mean time, can you remove:
Specific articles
(papers, ebooks, echapters, etc.)
and merge the two reserve entries into: Reserve a meeting room or study space.

**Comment by srunkows** [comment]
These updates are done and ready for review.

**Comment by tomadams** [comment]
Please link the following buttons:

Public Access -  https://cshl.libguides.com/NIH_Compliance
Data Management - https://cshl.libguides.com/datamanagementCSHL
Citation Software - https://cshl.libguides.com/endnote

**Comment by srunkows** [comment]
These links have been added and are ready for review.

**Comment by tomadams** [comment]
online-training-2 and meeting-rooms-2 both have a "-2" at the end of the page. Please eliminate that from the page URL.

Please create page for Science Informationist, with graphic from button on top-right of page text. (Content to follow).

**Comment by srunkows** [comment]
This is because Wordpress needs a unique name for each piece of content to create a link. I think since there are images that have been 'published' with the same name as the pages which were published after the image, is what's causing the pages to be appended with the number 2.  I will try changing the name of the image files to see if this will correct it. If not, I'll make sure that this doesn't happen on production. This is one thing about Wordpress that is a little fussy. Everything needs a unique name including images. I'll update you after I try renaming the images.

ok, I just renamed the online-training.jpg image and can now update the URL and remove the -2 from it. https://lib-review-cshl-core.pantheonsite.io/library/services/online-training/

I will do the same for the meeting rooms page/image. https://lib-review-cshl-core.pantheonsite.io/library/services/meeting-rooms/

**Comment by srunkows** [comment]
https://lib-review-cshl-core.pantheonsite.io/library/services/science-informationist/

**Comment by tomadams** [comment]
Please change the title, URL and graphic icon name from "Data Management Planning" to simply "Data Management".

**Comment by srunkows** [comment]
Done and ready for review https://lib-review-cshl-core.pantheonsite.io/library/services/

**Comment by tomadams** [comment]
Looks good.

Will create new issue for Orientation and Informationist, that I need to provide content for

**Comment by tomadams** [comment]
Please rename "Citation Software" icon to "Reference Management".

We want to shorten the bulleted list. Please only include:

    Creating/updating your faculty profile
    Problems accessing online journals
    Locating incomplete/incorrect citations
    Searches for articles on specific topics
    Setup alerts (PubMed, Web of Science, ScienceDirect, Scopus)
    Reference Management (EndNote, Mendeley, Papers, etc.)
    Reserve a meeting room or study space
    Questions about NIH public access policy
    Persistent Digital Identifiers (ORCID, DOI, etc.) 
    PMCIDs/submitting papers to PMC

We would like to reorder the icons:

Orientation
Library Help
Science Informationists
Public Access Compliance
Interlibrary Loan
Data Management
Reference Management (previously listed as Citation Software)
Remote Access
Workshops
Online Training
Study Spaces
Meeting Rooms
Thesis Binding
24-Hour Self-Checkout
Printing & Scanning
3D Printing

**Comment by srunkows** [comment]
> Please rename "Citation Software" icon to "Reference Management".
> 
> We want to shorten the bulleted list. Please only include:
> 
> ```
> Creating/updating your faculty profile
> Problems accessing online journals
> Locating incomplete/incorrect citations
> Searches for articles on specific topics
> Setup alerts (PubMed, Web of Science, ScienceDirect, Scopus)
> Reference Management (EndNote, Mendeley, Papers, etc.)
> Reserve a meeting room or study space
> Questions about NIH public access policy
> Persistent Digital Identifiers (ORCID, DOI, etc.) 
> PMCIDs/submitting papers to PMC
> ```
> 
> We would like to reorder the icons:
> 
> Orientation
> Library Help
> Science Informationists
> Public Access Compliance
> Interlibrary Loan
> Data Management
> Reference Management (previously listed as Citation Software)
> Remote Access
> Workshops
> Online Training
> Study Spaces
> Meeting Rooms
> Thesis Binding
> 24-Hour Self-Checkout
> Printing & Scanning
> 3D Printing

These updates are complete and ready for review.

**Comment by tomadams** [comment]
Looks great.

Can you change the following page URL:
remote-access-vpn => remote-access
datamanagementCSHL => data-management

**Comment by srunkows** [comment]
> Can you change the following page URL:
> remote-access-vpn => remote-access
> datamanagementCSHL => data-management

Remote Access url has been updated.

I do not have access to update URLs on https://cshl.libguides.com/ where the data management page lives.

**Comment by tomadams** [comment]
ok
