### ISSUE TITLE
Library Resources - E-Books

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#20]
Please add the material in the https://lib-review-cshl-core.pantheonsite.io/library/resources/e-books-by-subject/ page into the library/resource/e-books page above the "Elsevier E-books by Title" section.

Then eliminate the E-books by subject page.

**Comment by srunkows** [comment]
This is done and ready for review.

**Comment by tomadams** [comment]
Looks good.

Can you include the image of the blue button for E_books, into the top-right of the text, to keep the visual theme going.

**Comment by srunkows** [comment]
E-books image added.

**Comment by tomadams** [comment]
Thanks.

**Comment by tomadams** [comment]
Please remove the following text, (we no longer subscribe):

### Safari Tech Books Online

Over 24,000 e-books to choose from. Contact the Library to have book(s) swapped in.

**Comment by srunkows** [comment]
Done and ready for review:

https://lib-review-cshl-core.pantheonsite.io/library/resources/e-books/

**Comment by tomadams** [comment]
The title block:  ProQuest Ebook Central
seems larger then the rest. Can we have it the same size as the rest and have it be a link like the other resources.  Can you make the ProQuest EBook central graphic look a little bit more like a ghost button with a blue outline around it?

**Comment by srunkows** [comment]
These updates are done. https://lib-review-cshl-core.pantheonsite.io/library/resources/e-books/

I did my best with turning the proquest logo into a ghost button, but there are some issues with it. Because it's a transparent png when you hover over it the background turns blue and you sort of loss the text because it's dark grey.

The light grey stroke that used to be around the image is a bootstrap class "img-thumbnal" and the color can't be changed to blue. There are no other classes to have a blue stroke around an image. I could remove the image and just put ProQuest Ebook Central text instead or not make it a ghost button and put the grey stroke back.

**Comment by tomadams** [comment]
I like that fact that it behaves like a button when hovering over, the look is acceptable to me.

The second paragraph on the page, which is:

> Additionally, you can visit our E-books by Subject page for a comprehensive guide of e-books categorized by research areas.

Should be removed, since the page so reference is merged into this page itself and no longer exists as itself.

Interesting to see how the two images, will now layout, since the text might slide up a little.

**Comment by srunkows** [comment]
The second paragraph of text has been removed and the page is ready for review.

**Comment by tomadams** [comment]
In the first paragraph, please make the "Library Catalog Search" into a blue ghost button.

It was determined that the descriptive text under some of the headings provided no value and could be eliminated. Starting with "Book Series from Elsevier", turn the headings into a 2  columns of links, without the descriptions. The links in question are:

Book Series from Elsevier
Oxford English Dictionary
Oxford Scholarship Online
Springer Link
ADD Wiley Online Library =>  https://onlinelibrary.wiley.com/
REMOVE Wiley InterScience Molecular Biology Collection
REMOVE Wiley InterScience Medical Sciences Collection
REMOVE Wiley InterScience Pharmaceutical Medicine Collection
WormBook

**Comment by srunkows** [comment]
> In the first paragraph, please make the "Library Catalog Search" into a blue ghost button.
> 
> It was determined that the descriptive text under some of the headings provided no value and could be eliminated. Starting with "Book Series from Elsevier", turn the headings into a 2 columns of links, without the descriptions. The links in question are:
> 
> Book Series from Elsevier
> Oxford English Dictionary
> Oxford Scholarship Online
> Springer Link
> ADD Wiley Online Library => https://onlinelibrary.wiley.com/
> REMOVE Wiley InterScience Molecular Biology Collection
> REMOVE Wiley InterScience Medical Sciences Collection
> REMOVE Wiley InterScience Pharmaceutical Medicine Collection
> WormBook

These updates are done and ready for review.

**Comment by tomadams** [comment]
After seeing the results of removing the descriptions and just having a list of links, made it obvious that this E-Book page needs the same treatment as the Databases & Protocol page, with graphical buttons for the links to E-Book vendors. I have sent you those 400x150 images via email.

Please order the graphical links as follows (The original Proquest icon will be removed):
ProQuest E-Book Central
Wiley Online Library
Elsevier ScienceDirect  => https://www.sciencedirect.com/browse/journals-and-books?contentType=BK&contentType=HB&contentType=RW&contentType=BS&accessType=subscribed&accessType=openAccess
Springer Link
Oxford Scholarship Online =>  https://www.universitypressscholarship.com/browse?submittedFilterId=by-availability&isQuickSearch=true&pageSize=20&sort=titlesort&avail_3=unlocked&avail_4=free&avail_5=open
Oxford English Dictionary
WormBook

Please change the text to:

H1  E-Books

The library's collection of purchased E-Book are in the library's catalog and that is a great place to start searching for both print and E-Books. If you only want to see the E-Book listings, check the "Search only Electronic Books" box, in the search field of the Catalog. 

Add the existing "Library Search Catalog" button here. (center if possible).

Don't limit yourself to only what is in our catalog. Our major E-Book vendors have an extensive catalog of recent scientific and technical books from hundreds of leading publishers. For example, ProQuest EBook Central allows you to view the full text version of any book for 5 minutes. If you decide that the book is worthwhile, simply request the book directly on the website, and your request will be processed by a CSHL Librarian. From the Wiley Online Library, a book may be listed as "Token Access". Just contact a librarian, and we will quickly purchase the book for you. (Naturally, you need to be a member of the CSHL community.)

For details on using the Ebook Central, we have an Ebook Central LibGuide. <= existing sentence with link.

Now all of the vendor buttons appear here.

Then the rest of the page, starting with "E-Books by Subject"

**Comment by srunkows** [comment]
These updates are done and ready for review.

**Comment by tomadams** [comment]
Please place the "Library Search Catalog" button, between the first and second paragraphs.

**Comment by srunkows** [comment]
> Please place the "Library Search Catalog" button, between the first and second paragraphs.

Done and ready for review

**Comment by tomadams** [comment]
Great.
