### ISSUE TITLE
Orientation / Getting Started - a series of pages

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#21]
For Orientation / Quickstart, would like to have a series of pages, with a: title,  back/forward arrows for quick navigation,  large 16:9 jpg image at the top, and descriptive text underneath. The link from services, should go to the first page.

**Comment by srunkows** [comment]
Here's a draft of what I think you're looking for: https://lib-review-cshl-core.pantheonsite.io/library/services/orientation-getting-started/

**Comment by tomadams** [comment]
That structure looks good, just as long as the title can change for each page.

After looking at the "Orientation / Getting Started" name, I do not like the "/", since it is misleading in the breadcrumbs. Perhaps you can just simplify it to "Orientation", on the button and the title for the first page. I assume subsequent pages would just add a level of hierarchy e.g. library/service/orientation/page-2-topic.

**Comment by srunkows** [comment]
I updated the page name to just Orientation and changed the title in the box on the Services page.

https://lib-review-cshl-core.pantheonsite.io/library/services/orientation/

I also created a page 2 placeholder page, so you can get the feel of the button navigation and page title, URL, breadcrumbs, etc. at: 

https://lib-review-cshl-core.pantheonsite.io/library/services/orientation/Page-2/

**Comment by tomadams** [comment]
Structure looks good. I will need to provide some content.
