### ISSUE TITLE
Library - Resources - Newspapers and Magazines Rack

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#22]
I think we can rename the button and it's page to "Newspaper & Magazine Rack"
Copy the button image to the top-right of the content text.

Current print editions of various magazines and newspapers for your casual reading.

**Library Reading Room**
NY Times
Newsday
World Street Journal
Huntington News
The Leader
The Long Islander
Chronicle of Higher Education

All Press Print Journals
CSH Protocols
Genes & Development
Genome Research
Learning & Memory
RNA

Nature 
Science
Consumer Reports
Discover
American Scientist
The Economist
National Geographic
New Scientist
New Yorker
New York Magazine
Vanity Fair

MIT Technology Review

New York
Time
Travel & Leisure
Wired

**Racker Reading Room at Blackford**
NY Times
Newsday
Wall Street Journal
All Press Print Journals
Nature
Science

**Online Newspapers**
New York Times
Wall St Journal
The Financial Times
(email sherman@cshl.edu for directions to create your account.)

**Online Magazines**
[the existing page content with Flipters]

**Comment by tomadams** [comment]
Right before Online Newspapers, please add:

**Beckman, James and Delbruck**
CSH Press journals

**Comment by srunkows** [comment]
This is done and ready for review: https://lib-review-cshl-core.pantheonsite.io/library/resources/magazine-rack/

**Comment by tomadams** [comment]
Magazine rack looks good. Please spell out street in Wall St Journal under online newspapers. Also add links to those three online entries:
https://www.nytimes.com/
https://www.wsj.com/
https://www.ft.com/

**Comment by srunkows** [comment]
Done and ready for review.

**Comment by tomadams** [comment]
All right.

**Comment by tomadams** [comment]
The right hand side of the page looks empty and one has to scroll to see the bottom of the page.

Can we move the online magazines (CR, Health Letters), into a right hand column. Possibly with the icons slightly smaller, so that they can be stacked vertically. Possibly a 2/3, 1/3 column split, but do what looks nice.

**Comment by srunkows** [comment]
I tightened it up with columns and made the Health letter icons smaller. Let me know if this looks better.

https://lib-review-cshl-core.pantheonsite.io/library/resources/magazine-rack/

**Comment by tomadams** [comment]
OK
