### ISSUE TITLE
Library Services - Online Training

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#23]
Please create a page for this button, with the follow text:

The CSHL Library has subscribed to the O'Reilly Online Learning platform. This is a great resource to learn: a new skill,  the latest programming languages, cloud computing, machine learning, agile software development, or data science.  The training seat will give you unlimited access to: Interactive learning, prebuilt coding environments, Live Online training, learning paths and every O'Reilly  "Animal" technical books. 

**Access to today’s most important conversations** 
The platform includes thousands of hours of video from O'Reilly’s 16 global conferences, giving insider access to cutting-edge thinking from the world’s foremost technology and business leaders.

**Expertly curated, high-quality content**
O’Reilly’s savvy editorial team delivers exclusive books, videos, and learning experiences—including early release titles and case studies from leading organizations—plus resources from more than 200 of the world’s most respected publishers, including Pearson, Packt, Wiley, HarperCollins, and others.

**Proven learning formats**
The easy-to-follow, self-paced learning paths and interactive tutorials help users establish a knowledge base, build proficiencies, and develop new skills—their way. Write and run code in a live dev environment while you learn Kubernetes, Docker, Python, and more—right in your browser.

**Solve real-life problems fast**
Get quick answers to everyday problems while you work. Search and find the right information, use our interactive tutorials to grab a line of code, and get back to work.

**Certification prep**
 Direct paths to the official prep materials plus practice exams to become an AWS Certified Cloud Practitioner, Certified Information Systems Security Professional (CISSP), Microsoft Azure Administrator, and more.

**Time-saving tools**
Powerful search, personalized recommendations, and the ability to create custom playlists enable users to find and share what they need fast.

Please contact Tom Adams tadams@cshl.edu , if you would like to reserve a training seat. Note: the number of seats is limited.

**Comment by srunkows** [comment]
This is ready for review: https://lib-review-cshl-core.pantheonsite.io/library/services/online-training-2/

**Comment by tomadams** [comment]
Looks like I forgot to link to the website.

Right before the first h2 (Access to today’s most important conversations) Please insert:

If you have already be assigned a training seat, go directly to O'Reilly Learning, otherwise read on to find more about this and to reserve your seat.

Image from email (O'Reilly Learning)  => https://learning.oreilly.com

You can ignore the other image previously sent.

**Comment by srunkows** [comment]
I made this update but I'm not sure if I understood your comment about the image. I changed it out for the O'Reily image. Please review and let me know if this is correct or if you want the other training image that is in the box on the services page.

**Comment by tomadams** [comment]
In the second paragraph, just recently added, can you make "O’Reilly Learning" a blue ghost button with a link  to https://learning.oreilly.com

Let's keep the image for now.

**Comment by srunkows** [comment]
I added it, but it looks a little odd having a button in the middle of a sentence. Have a look and let me know what you think.

https://lib-review-cshl-core.pantheonsite.io/library/services/online-training-2/

**Comment by tomadams** [comment]
Looks good to me.
