### ISSUE TITLE
Library Services - Online Technical Training

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#24]
Will send you an image for the text. Please place the button image on the top-right of the page (as usual).

Please create a page, with the follow text:

The CSHL Library provides online technical training through the O'Reilly Online Learning platform. This is a great resource to learn: a new skill,  the latest programming languages, cloud computing, machine learning, agile software development, or data science.  The training seat will give you unlimited access to: Interactive learning, prebuilt coding environments, Live Online training, learning paths and every O'Reilly  "Animal" books. 

**Access to today’s most important conversations** 
The platform includes thousands of hours of video from O'Reilly’s 16 global conferences, giving insider access to cutting-edge thinking from the world’s foremost technology and business leaders.

**Expertly curated, high-quality content**
O’Reilly’s savvy editorial team delivers exclusive books, videos, and learning experiences—including early release titles and case studies from leading organizations—plus resources from more than 200 of the world’s most respected publishers, including Pearson, Packt, Wiley, HarperCollins, and others.

**Proven learning formats**
The easy-to-follow, self-paced learning paths and interactive tutorials help users establish a knowledge base, build proficiencies, and develop new skills—their way. Write and run code in a live development environments while you learn Kubernetes, Docker, Python, and more—right in your browser.

**Solve real-life problems fast**
Get quick answers to everyday problems while you work. Search and find the right information, use our interactive tutorials to grab a line of code, and get back to work.

**Certification prep**
 Direct paths to the official prep materials plus practice exams to become an AWS Certified Cloud Practitioner, Certified Information Systems Security Professional (CISSP), Microsoft Azure Administrator, and more.

**Time-saving tools**
Powerful search, personalized recommendations, and the ability to create custom playlists enable users to find and share what they need fast.

Please contact Tom Adams tadams@cshl.edu , if you would like to reserve a training seat. Note: the number of seats is limited.

**Comment by srunkows** [comment]
Ready for review: https://lib-review-cshl-core.pantheonsite.io/library/services/online-technical-training/

**Comment by tomadams** [comment]
This page is a duplicated of issue #23. Closing this issue since it is redundant.
