### ISSUE TITLE
Library Services - 3D Printing

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#25]
Use button graphics at top-right of text. Text for page, you can embed the URL into the text:

CSHL Library has a PRUSA i3 3D printer which is able to print objects in PLA plastic. The library gives instruction in 3D printing, so that you will be able to use the machine for training or prototyping purposes.

### 3D Printer Upgraded
We are happy to announce that our Prusa printer was upgraded to a MK2S, which is a nice boost from the original model. This new model was also award "Best 3D Printer" by Make: magazine.
Prusa i3 MK2S 3D printer Technical specs (September 2017 - MK2S edition)
- 31% bigger build volume – 10500 cm3 (25 x 21 x 20 cm or 9,84 x 8,3 x 8 in)
- Open frame design for easy use
- Integrated LCD and SD card controller (8GB included)
- Up to 40% faster printing thanks to the genuine E3D V6 Full hotend
- 0,4mm nozzle (easily changeable) for 1,75 mm filament
- Layer height from 0.05 mm
- Automatic mesh bed levelling
- Heatbed with cold corners compensation – for warpless 3D printing from any material
- Automatic skew axes compensation
- Hassle free PEI print surface - no glass, no glue, no ABS juice
- Supported materials – PLA, ABS, PET, HIPS, Flex PP, Ninjaflex, Laywood, Laybrick, Nylon, Bamboofill, Bronzefill, ASA, T-Glase, Carbon-fibers enhanced filaments, Polycarbonates...
- Specially optimized firmware for quiet printing

### 3D Models

There are many free libraries of 3D models, which are ready to print. No need to design the module yourself. Here are our favorites. 

**NIH 3D Print Exchange** The NIH 3D Print Exchange provides scientifically accurate models in formats that are readily compatible with 3D printers, and offers a unique set of tools to create and share 3D-printable models related to biomedical science. https://3dprint.nih.gov/

**MakerBot's Thingiverse** is a thriving design community for discovering, making, and sharing 3D printable things. As the world's largest 3D printing community, we believe that everyone should be encouraged to create and remix 3D things, no matter their technical expertise or previous experience. In the spirit of maintaining an open platform, all designs are encouraged to be licensed under a Creative Commons license, meaning that anyone can use or alter any design. https://www.thingiverse.com/

**Instructables** Explore. Shape. Make. Instructables was officially spun out of Squid Labs in the summer of 2006, and has gone on to grow from a modest hundreds of projects to over one hundred thousand (3D models are only a subset). The community that now calls the site home, is an amazing mix of wonder from around the world. Every day we continue to be amazed by the imagination, curiosity, and simple awesomeness of everyone who shares their creations with us on Instructables. https://www.instructables.com/

**GrabCAD Community** accelerates the design process by tapping into the largest source of mechanical engineering content and knowledge in the world. https://grabcad.com/library

**Smithsonian X 3D** launches a set of use cases which apply various 3D capture methods to iconic collection objects, as well as scientific missions. These projects indicate that this new technology has the potential not only to support the Smithsonian mission, but to transform museum core functions. Researchers working in the field may not come back with specimens, but with 3D data documenting a site or a find. https://3d.si.edu/

### CAD/CAM Software

**Onshape** is the first and only full-cloud 3D CAD system that lets everyone on a design team simultaneously work together using a web browser, phone or tablet. They offers a free pricing tier for Makers. https://www.onshape.com/

**Solidworks** An industry standard in 3D design. Complete set of packages, including rendering and testing. https://www.solidworks.com/

**OpenSCAD** is a software for creating solid 3D CAD models. It is free software and available for Linux/UNIX, Windows and Mac OS X. Unlike most free software for creating 3D models (such as Blender) it does not focus on the artistic aspects of 3D modelling but instead on the CAD aspects. Thus it might be the application you are looking for when you are planning to create 3D models of machine parts but pretty sure is not what you are looking for when you are more interested in creating computer-animated movies.  OpenSCAD is not an interactive modeller. Instead it is something like a 3D-compiler that reads in a script file that describes the object and renders the 3D model from this script file. This gives you (the designer) full control over the modelling process and enables you to easily change any step in the modelling process or make designs that are defined by configurable parameters. http://www.openscad.org/about.html

**AutoDesk 123D Design** is a free, powerful, yet simple 3D creation and editing tool which supports many new 3D printers. https://www.tinkercad.com/

**Rhinoceros** Rhino can create, edit, analyze, document, render, animate, and translate NURBS* curves, surfaces, and solids, point clouds, and polygon meshes. There are no limits on complexity, degree, or size beyond those of your hardware. https://www.rhino3d.com/

### Modeling Tools

**Blender** is open source software design for artistic modeling, think animated characters. Blender is able to do: Photo-realistic Rendering, Fast Rigging (transforming a model into a posable character), Animation tool set, Sculpting, Game Design, and Video Editing. https://www.blender.org/

**Silo 2** is a focused 3D modeling application with the ability to effortlessly switch between organically sculpting high-polygon models and precisely controlling hard-edged surfaces. It can be used for anything from creating 3D characters for video games and movies to quickly exploring 3D architectural ideas. https://www.nevercenter.com/silo/

### Alternative Software

**Adobe Illustrator** Long known for creating vector art (2D), You can use this tool for laser cutters. https://www.adobe.com/products/illustrator.html

**SketchUp** users are architects, designers, builders, makers and engineers. https://www.sketchup.com/

**Tinkercad** is an easy, browser-based 3D design and modeling tool for all. Tinkercad is also your perfect 3d printing companion – it allows you to imagine anything, and then design it in minutes! Tinkercad is part of the 123D family of free apps from AutoDesk (Makers of AutoCAD). https://www.tinkercad.com/

**Comment by srunkows** [comment]
Done and ready for review: https://lib-review-cshl-core.pantheonsite.io/library/services/3d-printing/

**Comment by tomadams** [comment]
Perfect.
