### ISSUE TITLE
Please remove target="_blank" from all Library and Archvies website links

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#26]
It is extremely annoying to have the new website pop-open a new tab or windows when clicking on a link. Can we please eliminate that behavior across all of the Library and Website pages. 

Please see here for further information:
[When to use target=”_blank”](https://css-tricks.com/use-target_blank/)

Thanks

**Comment by srunkows** [comment]
As a rule of thumb, all external links and PDFs are opened in a new tab. Only website links that are within the CSHL domain are opened in the same window. This practice is to ensure a good user experience allowing the user to explore the other site without having to hit the back button to get to cshl.edu. This practice prevents them from leaving our website entirely and never getting back to it. Also, this is how Bruce prefers links to external websites work.

If there are examples of cshl.edu links opening in a new window please let me know where they are and I will fix them.

There are some instances with custom fields that consider any page that do not originate in wordpress to be an external link. The code could be amended at some point, but not anytime soon, as it is very low priority compared with my other current coding tasks.

**Comment by tomadams** [comment]
Moved to futures milestones.
