### ISSUE TITLE
Library - Services - Training Workshop

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#27]
Please change the name of the page URL/Name to "Training Workshop" it is currently labeled as "Training Request". On the  Services appears correctly as: Training Workshop.

Please remove the following photo and text:                                               

photo of Adrian Gomez - CSHL Library Archives

Data Informationist Adrian Gomez is a neuroscientist who received his Ph.D. examining the neurobiological mechanisms of nicotine addiction. He then conducted postdoctoral research at Washington University (in St. Louis) School of Medicine where he focused on investigating the neural circuitry underlying reward-seeking behaviors; as well as developing and optimizing in vivo wireless neural devices to dissect the neural circuitry related to affective behavior.

**Comment by srunkows** [comment]
Done and ready for review:

https://lib-review-cshl-core.pantheonsite.io/library/services/training-workshop/

**Comment by tomadams** [comment]
Looks, good.

**Comment by tomadams** [comment]
We would like this page to be renamed "Workshops" from "Training Workshops", also with the Title/URL changed to match and the Icon label on the services page.

**Comment by srunkows** [comment]
Done and ready for review: https://lib-review-cshl-core.pantheonsite.io/library/services/workshops/

**Comment by tomadams** [comment]
Good.
