### ISSUE TITLE
Archives - Homepage

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#29]
Please save the existing /archives page to /archives-2

Copy the content that is in archives/about to the /archives page. The page title should be called "Archives".
Rearrange existing content so that the icons appear in four columns:
Personal Collections,                          Special Collections,                       BGI/Genetech,                        Center for Hummanities

Not that BGI and Genetech in the third column are stacked boxes and are the same height as the rest. There is not a "BGI/Genetech" label, just two separate boxes. They might just be ghost buttons.

Now add "CSHL Archival Resources" section with:

`Additional online resources have been created and maintained by CSHL Archives. Our archival resources include:

    CSHL ArchivesSpace - Finding aids of collections within the CSHL Archives.
    Oral History - Over 100 interviews with prominent molecular biologists.
    History of Science - Science history meetings on topics in molecular biology. Videos of presentations online.
    CSHL Symposia - Iconic annual symposium at CSHL.
    Archives Repository - Digitized collections of Watson, Brenner and Muller.
    Digital Collections - Digitized Collections archived with Digitool.
    Guide to the HGP - An Annotated Scholarly Guide to the Human Genome Project.
    CSHL Archives Website - Collections listed.
    Center for Humanities - Exhibits, Fellowships, Talks, Events, Scholarship.
`
with the following URLs:

http://archivesspace.cshl.edu/
http://library.cshl.edu/oralhistory
http://library.cshl.edu/Meetings
http://library.cshl.edu/symposia
http://libgallery.cshl.edu/
http://archives.cshl.edu/
http://library.cshl.edu/Guide-to-HGP/
http://cshl.edu/archives
http://cshl.edu/center-for-humanities

Feel free to make the above resources into two column if it looks better.

Finally add a line of CSHL Instagram, photos as the last elements.

**Comment by srunkows** [comment]
I have a few questions/need clarification on these changes. How you answer will help me determine the correct implementation. The code will need to be changed for the template and will save me from having to make changes if I didn't fully understand what you need.

1) What is your reasoning for saving the Archives landing page as archives-2? Is it to do a side by side comparison after the new landing page is created or do you intend on repurposing the content and just want to keep a record of it?

2) Should the new version of the page keep the carousel or do you plan on eliminating it entirely from the landing page?

3) I'm not sure what you want the BGI/Genetech box to be. You refer to it as 'stacked boxes' There is no mechanism in the code to have 2 stacked boxes in a column. I would have to start a new row and it would be in the first column not the 3rd.

The boxes I have been using are technically called 'cards.' But there is an option for a 'tile' box. A tile box allows for multiple links within the box, but you loss the ability to make the entire box a single clickable link. The look is the same as a card. I should be able to add 2 ghost buttons below the title. You can see an example of this on the dnalc branch. Their tiles have multiple links within the box (just not ghost buttons): https://dnalc-cshl-core.pantheonsite.io/dnalc/resources/websites/ Each of these boxes have been implemented as a 'tile.'

4) Will you be implementing a content feed on this page like on the Library landing page?

5) I need clarification on the last item, a line of CSHL instagram, photos. Do you want an actual Instagram feed similar to what we have on the bottom of the homepage (just above the blue footer): https://www.cshl.edu/ and on the Banbury landing page (just above the black section footer): https://www.cshl.edu/banbury/ If you want an Instagram feed you will need a Juicer account. This is what drives the social feeds on the website. https://www.juicer.io/

6) Are there any other elements you can think of that you want on the Archives landing page? I'd like to do a single round of code updates to the template, if possible, instead of several. (thanks!)

**Comment by tomadams** [comment]
To answer your questions:

1. Just wanted to save a record of the original design. Do not expect to repurpose.
2. Carousel gone
3. Eliminating the BGI/Genetech box, will change it to a graphic link, placed elsewhere
4. No content feed
5. Might have highlights from collection, not instagram feed
6. I can't image that changes will not be revised, no matter how perfect the initial design is. I will try my best.

### Updated Design
### Archives
CSHL Archives identifies, collects, preserves and provides access to original materials documenting the history of molecular biology and genetics worldwide. This includes materials related to the history of CSHL and its role in modern biology. Established in 1972, CSHL Archives develops and participates in broad scholarly and educational programs, bringing together scientists, scholars, journalists and the public on topics at the intersection of science and history.

After first paragraph, want to have a 2/3 - 1/3 column split for the page. Otherwise just start page with two columns.

**[Left Hand Column]**
[Sold blue buttons]
Center for Humanities
History of Science Meetings 
Funding Opportunities

Contact the Archives [ghost button like appears on individual collections]

**Access to Materials**
Access to archives is by appointment only. Appointments are available Monday-Friday: 8AM-4:30PM. Please contact 516-367-8414 or archives@cshl.edu to schedule you appointment and on the material availability. 

**Permission & Fees**
Consult our _Permission & Fees_ page to determine the cost and restrictions of using materials in the archival.

**[Right Hand Column]**
### Guide to the CSHL Historical Collection (this header will eventually be a link)
The guide provides context to the CSHL archival collection in the history of molecular biology in a theme based presentation of topics and the various parts of the CSHL collections that are relevant. A great starting place, when you want tour of the field.

Here we now want three buttons like appear in the archives/about page
Personal Collections
Institutional Collections  (Was previously call Special collections)
Oral History

Followed by, the "CSHL Archival Resources" section, as described before.

No instagram, just tiles with images, title, and description of interesting object in our collection.

**Comment by srunkows** [comment]
I updated the template code base for the Archives landing page and content as explained above.  It is ready for a preliminary review.

I need some additional content: Instagram stuff and images for the row of boxes/buttons for personal collections, institutional collections and oral history.

**Comment by tomadams** [comment]
Please use the same images found in https://lib-review-cshl-core.pantheonsite.io/archives/about/ for the Personal Collections and Institutional Collections.

Will work on the rest.

**Comment by srunkows** [comment]
Done and ready for review.

**Comment by tomadams** [comment]
Just emailed picture for Oral History graphic.

**Comment by srunkows** [comment]
Uploaded and ready for review.

**Comment by tomadams** [comment]
We want to move things around on the Archives Home page: /archives

Everything currently under the three pictures, should be removed. This includes the "Additional online resources..." and "Instagram stuff".

The very first paragraph, should be moved to the bottom of the page (underneath the three pictures), with a h3 tag of: "CSHL Archives' Mission".

Add a h3 tag of "Collections", right above the three current pictures.

Add the picture of the sextant, to the left hand side of the "Guide to the CSHL Historical Collection" tag and following test. Label the image as "Guide to Collections", this will be a external link but I do not have a URL for it yet.

**Comment by srunkows** [comment]
These updates are done and ready for review.

I wasn't exactly sure how you wanted the Guide to Historical Collection to be rendered, as a heading, caption under image, or text within the paragraph. I left it as a heading, please let me know if I made the correct choice or if it needs to be changed.

**Comment by tomadams** [comment]
As mentioned in the #43 issue, the personal and institutional collection pictures and links are moving to the Collection Flowchart page. The Oral History picture and link will move to the Center for Humanities page. So what is left?

# Archives [1/2]    . . .  . . . . thin archives header graphic [1/2]
## Story of the CSHL Archives [left 2/3 column]
The CSHL Archives strives to develop novel ways of presenting and preserving the records of the discoveries in biomedical sciences as a topic of historical interest. We try to bring together important figures in the history of the molecular biology and genetics fields by presenting biographical information, collecting the original materials that these individuals generated over their careers and collecting oral history interviews with them. As a result, we will be able to merge discussions of the past and the future, thereby framing cutting-edge research in terms of detailed knowledge of the past. We are focusing on creating a “living history” of important aspects of molecular biology and genetics research that blend the traditional discussions of current scientific research with lectures on the history of science; scholarly works; using our collections in public exhibitions; and scientific meetings in which the pioneers of the field interact with the current scientific community.

### [Three image/title/description boxes horizontal]
1. Guide to the CSHL Historical Collection 
The guide provides context to the CSHL archival collection in the history of molecular biology in a theme based presentation of topics and the various parts of the CSHL collections that are relevant. A great starting place, when you want tour of the field. [Sextant picture]
2. Funding Opportunities
Fellowships, Internships & Travel Grants for Scholars, Researchers, Writers and Filmmakers.
3. Center for Humanities
The Center for Humanities and History of Modern Biology at CSHL is to promote an understanding of how modern biology has impacted history and the cultural ramifications of that discipline over time.
[With regards to these three boxes, want to make sure that it appears clickable, right now only see a slight fade on the title, perhaps additionally shift the color of the box itself.]  
## [right 1/3 column]
A solid blue button "CONTACT AN ARCHIVIST" button. Followed by the existing text of "Access to Materials" and "Permissions and Fees". No other buttons will appear.

**Comment by srunkows** [comment]
I updated the Archives homepage. I couldn't remember what images you want to represent Funding Opportunities and Center for Humanities. I reused the sextant image for the guide to collections box.

https://lib-review-cshl-core.pantheonsite.io/archives/

**Comment by tomadams** [comment]
From the latest discussion this morning with the team.

Make the first card plural.
Guide to the CSHL Historical Collection => Guide to the CSHL Historical Collections

This is the replacement text at the top of the page.
### Story of the CSHL Archives
Welcome to the CSHL Archives, a major repository of primary material on the history of the life sciences and medical research in the twentieth and twenty-first centuries. In addition to institutional records from the lab, its precursor institutions, and its funding bodies, the archives contain personal collections of nearly two dozen significant individuals from CSHL and around the world, a large repository of oral-history interviews, and documents from nearly a century’s worth of international symposia on the life sciences.

### [Replace the funding graphic with an actual pictures]
Tom will locate and provided.

### [Cheerful Colors / Graphics]
Looking for suggestions from Sue on what we can do to punch up the main archives landing page.

**Comment by tomadams** [comment]
I have just emailed you a new image for the Funding Opportunities.

**Comment by srunkows** [comment]
> From the latest discussion this morning with the team.

The text changes have been made and I added the new Funding Opportunities image.

As for making it look nicer, maybe we can do a banner image below the Archives heading and above the Story of the CSHL Archives heading. Something not too tall. Not sure if you have a single iconic image that you typically use for the Archives. I was thinking a photo of the Library building, but I'm not sure if that would be iconic enough?

**Comment by tomadams** [comment]
To see what a banner image looks like, I tried the following:
``` <div class="col-xs-12 col-md-8 col-lg-7 col-lg-offset-1 top-margin-10">
	<style>
                .crop-square {object-fit: cover; object-position: center; height:350px; width: 25%;}
		.crop-long {object-fit: cover; object-position: center; height: 350px; width: 46%;}
                #content {background-image:linear-gradient(to right, #ffe1e152 67%,#eae6d800 100%);}
	</style>
<img class="crop-square" src="https://photos.smugmug.com/photos/i-Kpz5FXR/0/963f8018/X3/i-Kpz5FXR-X3.jpg" width="33%">
	<img class="crop-long" src="https://photos.smugmug.com/photos/i-KHJ5NHH/0/bcdb0feb/O/i-KHJ5NHH.jpg" width="33%">
	<img class="crop-square" src="https://photos.smugmug.com/SmugVault2/JPEGSMUGVAULT/n-4MrqrT/2015-06-06-TEST/i-MjZ7fTh/0/fd42db12/XL/IMG_0126-XL.jpg" width="33%">
<h3 class="top-margin-0">Story of the CSHL Archives<div></div></h3>
```
Which also added a slight background gradient to the page.

![image](https://user-images.githubusercontent.com/1951133/101042003-b1192800-354a-11eb-85c3-cfa5c9189d1f.png)

I am waiting to see how the team responds to the possible modification. Do you have any additional design elements that can be added?

**Comment by tomadams** [comment]
After a few more refinements, were are looking at this:
![image](https://user-images.githubusercontent.com/1951133/101107640-b5703000-35a0-11eb-87a8-70239e0ef85d.png)
Single top picture. No "Story of the CSHL Archives" sub-heading. Time for appointments, ends at 4pm (not 4:30pm). Added address. The text should say "nearly three dozen" instead of two dozen.
We should always use "CONTACT AN ARCHIVIST" on the buttons, not "CONTACT THE ARCHIVES", was we have used on some of the previous pages.
The code I used, so I don't forget is:
```
<div class="col-xs-12 col-md-8 col-lg-7 col-lg-offset-1 top-margin-10">
	<style>.crop-square {object-fit: cover; object-position: center 20%; height:350px; width: 98%;}
		.crop-long {object-fit: cover; object-position: center; height: 350px; width: 46%;}
	</style>
<img class="crop-square" src="https://photos.smugmug.com/photos/i-gnj5cv8/0/dc93d137/O/i-gnj5cv8.jpg" width="33%">
```

**Comment by srunkows** [comment]
Updates made and ready for review. https://lib-review-cshl-core.pantheonsite.io/archives/

**Comment by tomadams** [comment]
Looks very good. Mila wanted to make the following text change on the right hand side.

### Access to Materials
Archives is open from 8 am to 4 pm weekdays. Access to archives is by appointment only.

For appointments, reference or research requests, and questions about our collections please contact +1 516.367.8414 or e-mail: archives@cshl.edu

**Comment by srunkows** [comment]
> Looks very good. Mila wanted to make the following text change on the right hand side.
> 
> ### Access to Materials
> Archives is open from 8 am to 4 pm weekdays. Access to archives is by appointment only.
> 
> For appointments, reference or research requests, and questions about our collections please contact +1 516.367.8414 or e-mail: [archives@cshl.edu](mailto:archives@cshl.edu)

This is done and ready for review.

**Comment by tomadams** [comment]
Great.
