### ISSUE TITLE
Library - Fat Footer

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#32]
Library  [Social Icons]

**About**
The Library
Contact
Policies
Library News
[space]
[Phone icon]+1 (516) 367-6872
[Envelope icon]libraryhelp@cshl.edu

**Resources**
Library Resources
Journals
Library Catalog
Databases & Protocols
Institutional Repository
Faculty Profiles
Elements
LibGuides

**Services**
Library Services
Interlibrary Loan
Library Help
Public Access Compliance
Data Management
Science Informationist
Workshops
Online Training

Study Spaces
Meeting Rooms
Printing & Scanning
Orientation
3D Printing
Thesis Binding
24-Hour Self-Checkout

**Comment by srunkows** [comment]
This is ready for review. I think I got everything.  2 things:

I don't know what link 'Elements' in the Resources column should point to.
We do not currently have the ability to add a blank space or text to the footer. So I can't add the phone number or email to the About column. This will be addressed in phase 1 of the Navigation update. The way the consultants implemented the section footer is too rigid and does not allow for anything other than links to pages or external websites

**Comment by srunkows** [comment]
Nevermind about the Elements link. I found it and will add it now.

**Comment by tomadams** [comment]
I find the black background on the footer a little too extreme. Can we go with:

.footer-bg-black {
    background-color: #024b80cc;

**Comment by tomadams** [comment]
Sue,
But those are links.
```
<a href="tel:+15163676872">[Phone icon]+1 516-367-6872</a>
<a href="mailto:libraryhelp@cshl.edu">[Envelope icon]libraryhelp@cshl.edu</a>
```

**Comment by srunkows** [comment]
> Sue,
> But those are links.
> 
> ```
> <a href="tel:+15163676872">[Phone icon]+1 516-367-6872</a>
> <a href="mailto:libraryhelp@cshl.edu">[Envelope icon]libraryhelp@cshl.edu</a>
> ```

The way the consultants coded up the section footer menus, does not allow for adding these kinds of links, it turns everything into a fully qualified link, i.e. 'https://' so when I add email links or phone links it adds http:// to the link and when clicked you get a 404 page not found error. We recognized this shortcoming several months ago along with some other shortcomings on the backend administration of them. I'm hoping to get these issues resolved before we launch your site.

**Comment by srunkows** [comment]
> I find the black background on the footer a little too extreme. Can we go with:
> 
> .footer-bg-black {
> background-color: #024b80cc;

I can't change this just for your section, it would require a change to all section footers across the website. We'll take the recommendation under advisement when I make improvements to the code base that drives these footers.

However, hex colors are 6 digits and you have provided 8 so I'm not exactly sure what color you are recommending.

**Comment by tomadams** [comment]
The last 2 are the alpha channel, so we can pick up a little of the background image.
![image](https://user-images.githubusercontent.com/1951133/93358892-05e0b880-f810-11ea-9b8d-76d0cd7d4a49.png)

**Comment by srunkows** [comment]
Thanks for your input and clarification on background color. 

Blue was our original choice of color for the section footers, but was rejected because it didn't provide enough visual separation between the institutional footer and section footers. 

We tried several other colors and the general consensus from the user testing we did was that the black brought importance to the section footer and made it more visible as a navigation aid for that section and was acted upon more instead of being ignored.

**Comment by tomadams** [comment]
For the large icons at the top of the Library Fat Footer...

The envelope icon goes to the Graduate School Contact page. Should go to the library contact page. (There seems to be a library/contact as well as a library/about/contact)

The youtube goes to the archives youtube. It should go to: https://www.youtube.com/channel/UCqr9vXGZW_RwH0Qa-kahatw

**Comment by srunkows** [comment]
> For the large icons at the top of the Library Fat Footer...
> 
> The envelope icon goes to the Graduate School Contact page. Should go to the library contact page. (There seems to be a library/contact as well as a library/about/contact)
> 
> The youtube goes to the archives youtube. It should go to: https://www.youtube.com/channel/UCqr9vXGZW_RwH0Qa-kahatw

These 2 items are now fixed and ready for review.

**Comment by tomadams** [comment]
OK
