### ISSUE TITLE
Library Services  -Orientation & Informationists

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#33]
Need content for Sue.

**Comment by tomadams** [comment]
Sent 21 PNG slides via email on 9/23/2020 for Orientation page.

**Comment by srunkows** [comment]
Updated and ready for final review. https://lib-review-cshl-core.pantheonsite.io/library/services/orientation/

**Comment by tomadams** [comment]
Orientation looks marvelous.

Tom needs to get content for the Informationists.

**Comment by tomadams** [comment]
Science Informationist Webpage:

### Meet our Informationists

Roxanne Karimi (karimi@cshl.edu) joined CSHL as a Data Science Informationist in 2020. Dr. Karimi received a PhD in Biology from Dartmouth College and has a background in environmental health, ecology, and data synthesis. 

Matt Dunn (dunn@cshl.edu) joined CSHL as a Research Informationist in 2017.  Dr. Dunn received a PhD in Molecular and Cellular Biology from the Weill Cornell Graduate School of Medical Sciences and has a background in developmental biology, evolutionary biology, and human genetics.

### Hello CSHL scientific community!
We are formally trained scientists now working at the CSHL Library, and our role is to help support you with a range of services throughout the full research cycle. 

In short, if you are in need of assistance at any stage of your research, from inception to publication, consult with us. We are trained and enthusiastic to assist you, and to take some of the 'search' out of your research. We have also created a suite of subject LibGuides with more information to get you started on various research-related topics. 

We provide assistance with the following to make your research stronger and your life easier via instruction (training workshops), individual, and group consultations:
•	Literature, Evidence and Data Searches
•	Data Management Planning, Organization, Publishing, and Sharing  
•	Systematic Reviews and Syntheses 
•	Research Paper, Poster, or Presentation Development
•	Measuring / Enhancing Research Impact 
•	Compliance with funder Public Access Guidelines
•	Organizing, Writing, and Editing Scientific Communications
•	Effective Strategies for Writing Grants

_Place the following on a side or in a panel_

 “Science informationists collaborate with scientists to enhance their research by helping them to assess its impact, and to curate and manage data. They make knowledge accessible, for example, by using their skills in tailoring vocabularies and ontologies. They preserve and showcase their institutions' intellectual output by building networked repositories, and they work with publishers to improve standards, platforms, publication models, and search facilities in the interests of better communication.”
Pollock L. "Librarians or science informationists?" Nature 490, 343 (2012).

(The citation on the line above should hyperlink to this URL: https://www.nature.com/articles/490343d

Keep Calm graphic (send via email) at bottom.

**Comment by srunkows** [comment]
Ready for review. https://lib-review-cshl-core.pantheonsite.io/library/services/science-informationist/

Not exactly sure I got the placement of the images right. Please let me know.

**Comment by tomadams** [comment]
Sent you a square image, which might look better. Keep that location.

**Comment by srunkows** [comment]
> Sent you a square image, which might look better. Keep that location.

Added and ready for review

**Comment by tomadams** [comment]
Perfect.
