### ISSUE TITLE
Library - About - Contact - Staff

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#35]
Please remove:
Adrian Gomez

and add:

Roxanne  Karimi        Science Informationist, Data Management Specialist       karimi@cshl.edu
Alistair Sponsel           Historian of Life Science                                                  sponsel@cshl.edu

Modify Matt Dunn to:  
Science Informationist, Scholarly Communication Specialist

**Comment by srunkows** [comment]
These updates are done and ready for review

**Comment by tomadams** [comment]
ok
