### ISSUE TITLE
Online Librarian (section footer code)

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#37]
_This issue was copied out of a previous issue, to make it stand alone and to be able to close the other issue._

We would like this library contact information appear in two places.
1. On the main library home page, in the space below the three large blue buttons on the right.
2. On the Phone & E-Mail tab under:  https://lib-review-cshl-core.pantheonsite.io/library/about/contact/

### Contact the Library

Phone: +1 516.367.6872   ==>  href="tel:+15163676872"
Hours: 9 A.M. to 10 P.M.
Email: libraryhelp@cshl.edu  ==> href="mailto:libraryhelp@cshl.edu"
`<div id="libchat_4a69076e6304e7fbee0329da6eb6b343"></div><script src="https://cshl.libanswers.com/load_chat.php?hash=4a69076e6304e7fbee0329da6eb6b343"></script>`

Instead of the words: Phone, Hours and Email use Font Awesome 5 icons for a phone, clock  and email.
Phone and email should be links. The above code will place a Online Librarian button right below the email.

### Ask Us slider on all library pages
Please also add our online librarian code (libanswers) to all of our library pages, by placing the following into the library footer, header, or wherever might be the best place to put it.

Please add the following widget on every library page. Perhaps in library footer, or another common library section.:

`<div id="libchat_ea47adad5d176e66a85915d07c2db2c0"></div><script src="https://cshl.libanswers.com/load_chat.php?hash=ea47adad5d176e66a85915d07c2db2c0"></script>`

**Comment by srunkows** [comment]
> * On the main library home page, in the space below the three large blue buttons on the right.
> * On the Phone & E-Mail tab under:  https://lib-review-cshl-core.pantheonsite.io/library/about/contact/

These updates are done and ready for review.

I need to add a style to the css to make sure the font matches all the buttons on the website. Right now it's defaulting to the website serif font instead of the sans serif font we use for buttons.

**Comment by srunkows** [comment]
> ### Ask Us slider on all library pages
> Please also add our online librarian code (libanswers) to all of our library pages, by placing the following into the library footer, header, or wherever might be the best place to put it.

I think the best place for this content will be in the black section footer. The section footer code needs revamping to allow for content other than links to pages before this can be done. 

Maybe this should be made into it's own issue so it can b tracked separately.

**Comment by tomadams** [comment]
Please add the following widget on every library page. Perhaps in library footer in the section where the **SOCIAL MEDIA icons** are, or another common library section.:

`<div id="libchat_ea47adad5d176e66a85915d07c2db2c0"></div><script src="https://cshl.libanswers.com/load_chat.php?hash=ea47adad5d176e66a85915d07c2db2c0"></script>`

For all of the Archives and Center for Humanities pages, please use the following code:

`<div id="libchat_67b13dcbfae4f77bf5fe1b76e8411ac7"></div><script src="https://cshl.libanswers.com/load_chat.php?hash=67b13dcbfae4f77bf5fe1b76e8411ac7"></script>`

-Tom

**Comment by srunkows** [comment]
as a test, I added the script to the Archives footer and it shows up as an 'Ask Us' button on the right side of the Archives pages. It didn't throw any errors. The only issue I see is that on smaller screens it covers up content as the page is scrolled.

**Comment by tomadams** [comment]
Looks good to me. Your concern about smaller screens is noted, but I do not expect it to be that much of an issue, since scrolling does reveal the text.

**Comment by tomadams** [comment]
To move the "AskMe" button a little lower, use the following code:
`<style>
.lcs_slide_out-r {top: 25%; }
</style>
`
