### ISSUE TITLE
Search for Memory Board

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#38]
### Not finding Memory Board
Mila is trying out the search with regards to not being able to do both library and website pages. When we type in “Memory” into the library search, we are expecting to pull up “Memory Board”, which is on the https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/exhibits/ page. If we filter by “Library” or “CSHL Archives” that page never appears. Why is that? 
When we search without any filters, we do see “Exhibits” listed at the bottom of the page without any descriptive text, but nothing that signifies “Memory Board”. Does that type of page needs to be redesigned, so that each exhibit is its own page, or should that page be created with as a list of blog entries on that page?
We will need to make sure that when Mila types in Memory, we should see “Memory Board” in the search results, hopefully near the top.
Are any Booleans or quotes able to but put into the search field? Nothing seemed to work for me.

### Sue: Found template problem with search
Search: I did some investigation on this issue. Turns out it's not just on your pages, it's across the entire website. It appears that certain templates the consultants built don't work well with the search plugin they developed/implemented.  Once I changed the template for the Exhibits page, searching for 'Memory' now returns the exhibits page in the results with a summary paragraph with 'memory board.'  
 
Thank you for pointing this out. It made me delve deeper into the code and uncover the issue. This explains why some search results come back with just the page and no summary paragraph, which had puzzled me for some time now. This issue will be added to my list of items that need to be fixed (other items include checkboxes instead of radio buttons in search filtering, better site wide navigation, etc.). I do not know when this issue or the others will be fixed.
 
Your question regarding the boolean search: if you enter 2 or more search terms the system defaults to an 'AND' search so quotes are not necessary.

### Tom: Seeing only OR search of terms
With regards to the search functionality, I am not seeing the behavior you are describing. It appears more like a “OR” search, thus quotes would be valuable. When you type in the following, the number of search results returned is:
“memory” =>159
“board” => 187
“memory board” => 333

### Sue: Dev Branch had "OR", production site has "AND"
I just checked the settings for the search plugin and it was set to OR. 

The search settings have been updated on your branch (lib-review) to do an AND.  Please try the search again and let me know if the results are better.

**Comment by tomadams** [comment]
All looks good now.

**Comment by srunkows** [comment]
I tweaked the search plugin settings and updated the code to make it more compatible with custom templates. Search results now return summaries for the majority of results. It's working much better in production now.  The code was pushed down to the lib-review branch and search plugin settings tweaked.

If there is no summary returned in the results it could be 1 of 2 reasons:

1) there is no intro paragraph on the page
2) there is no excerpt for the page
