### ISSUE TITLE
Archives - Ellen Brenner

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#40]
Please change all occurrences of:
Internship ==> Fellowship
Intern ==> Fellow

Also shorten the URL from:
grants-fellowships/ellen-brenner-memorial-internship-2 to
grants-fellowships/ellen-brenner

https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/grants-fellowships/ellen-brenner-memorial-internship-2/#about-the-award

**Comment by srunkows** [comment]
This is done and ready for review. The new link is https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/grants-fellowships/ellen-brenner/

**Comment by tomadams** [comment]
On the page above, https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/grants-fellowships/
please also change the title of the page from Internship to Fellowship.

**Comment by srunkows** [comment]
> On the page above, https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/grants-fellowships/
> please also change the title of the page from Internship to Fellowship.

This is now fixed and ready for review
