### ISSUE TITLE
Archives - Collections (top-level)

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#43]
The Personal, Institutional and Oral History boxes (with pictures) from the original mail page, will be incorporated into each section. 4 additional images will be chosen for the remaining sections.

### COLLECTIONS FLOWCHART
This section of the guide is systematic inventory of all the contents of the CSHL’s archives and related CSHL historical collections.  

### Institutional collections
 (also known as special collections). The institutional collections consist of documents produced by the laboratory and its various precursor institutions. CSHL has a complex institutional history, and researchers interested in a particular chronological period may need to consult records from multiple “institutions,” as well as relevant personal collections (see below) of researchers and administrators from the period.
### Personal collections
These collections contain documents and other materials amassed by individuals, many (but not all) of whom worked at Cold Spring Harbor for a portion of their careers. Some personal collections contain notable records relating to the institutional history of CSHL; for example, the Norton Zinder Collection (NDZ) includes minutes of CSHL trustees’ meetings attended by Zinder.
### Oral history collection
This consists of video recordings of 209 interviews, discussions, and conversations with a total of 223 participants in postwar molecular biology, genetics, biotechnology, and medicine. Since the discovery of the double helix in 1953, the molecular and genomic revolutions in science and medicine have fostered extraordinary changes in everyday life, including new types of vaccines and disease therapies, genetic modification of crops, and the inclusion of DNA evidence in the legal system. Our interview subjects include researchers and their family members, university administrators, civil servants, biotech entrepreneurs, and cultural practitioners such as science writers and visual artists who have commented on modern biomedicine. The recordings average about 90 minutes. 124 of the recordings have already been transcribed, but more transcriptions are being made every month.
### History of science meetings
These meetings held at CSHL bring participants who shaped a significant field of scientific research together with current practitioners, educators, and historians of that field. CSHL staff recorded and photographed each meeting and preserved speakers’ slide presentations, which are being continually added to a dedicated web portal.
### Rare books collection
Held by the CSHL library, the rare book collection contains some 2,500 books related to work at the laboratory and its precursor institutions. Areas of concentration include early twentieth-century animal and plant genetics and monographs and reports on studies of human heredity and eugenics, including bulletins of the Eugenics Record Office.
### CSHL Institutional Repository
The institutional repository contains bibliographic records and many full digital copies of work published by members of the lab and its precursor institutions, dating back to the 1890s.

**Comment by srunkows** [comment]
This page has been built. Some of the summary text in the boxes is long, you may want to consider shortening some of them Also, I couldn't remember if you sent images for History of Science Meetings, Rare Book Collection, Repository and Memory Board.

https://lib-review-cshl-core.pantheonsite.io/archives/collections/

**Comment by tomadams** [comment]
Thanks for uploading the images.

Can you not use cards on this page. I was thinking more of a paragraph style, with the title in bold and ALLCAPS font. The images floating on the right hand side. Possibly a little wider left hand margin.

![image](https://user-images.githubusercontent.com/1951133/100657326-176c3380-331c-11eb-8b2c-3394395e96b1.png)

**Comment by tomadams** [comment]
Text for the Rare Book and Memory Board:

#### Rare Book Collection
The Rare Book Collection encompasses 352 linear feet and over 2,500 books from the early day of the history of molecular biology and genetics. This collection is an invaluable resource for studies on genetics in the early part of this century, dealing with both animal and plant genetics. There are books on embryology and experimental biology, which are a valuable resource for individuals carrying out historical research on experimental biology. There are also books related to eugenics, in the United States in the early part of this century. As might be expected, the collection of eugenics texts is especially comprehensive, including books from Europe. In addition, there is a remarkably large collection of books on anthropology. 

#### MemoryBoard
The Memory Board is an experiment in interactive storytelling. The Memory Board provides a forum for scientists, administrators, support staff, trustees, students and visitors to share their memories about the evolving history of Cold Spring Harbor Laboratory, a center for the biological sciences, since 1890.

**Comment by srunkows** [comment]
> Can you not use cards on this page. I was thinking more of a paragraph style, with the title in bold and ALLCAPS font. The images floating on the right hand side. Possibly a little wider left hand margin.

I did one as an example (I left the cards for now). Have a look and let me know what you think. We don't use all caps on any text so I made it into a heading instead that links to the page. Headings are better for SEO and ADA.

**Comment by tomadams** [comment]
I like you example. Please convert the rest.

**Comment by srunkows** [comment]
> I like you example. Please convert the rest.

this is done

**Comment by tomadams** [comment]
Looking really good. Please update with the latest "Archives Right Sidebar" #45 using col-lg-2, and I think that page will be done.

**Comment by srunkows** [comment]
Right sidebar updated and ready for review. https://lib-review-cshl-core.pantheonsite.io/archives/collections/

**Comment by tomadams** [comment]
Please use the latest "Archives Right Sidebar", which includes "The Guide" button at the top of the blue buttons and the "Availability of Materials" under the buttons.

**Comment by tomadams** [comment]
In addition to updating the right sidebar, please fixed the link for:
Rare Books Collection and the Learn more... ==> https://lib-review-cshl-core.pantheonsite.io/archives/institutional-collections/rare-books/

**Comment by srunkows** [comment]
> Please use the latest "Archives Right Sidebar", which includes "The Guide" button at the top of the blue buttons and the "Availability of Materials" under the buttons.

This is done.

> In addition to updating the right sidebar, please fixed the link for: Rare Books Collection and the Learn more...

This is done.

Page is ready for review.

**Comment by tomadams** [comment]
Great.
