### ISSUE TITLE
Archives - Guide to the CSHL Historical Collections

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#44]
## GUIDE TO THE CSHL HISTORICAL COLLECTIONS

There are three main ways to use this guide:
1. you can begin with a **flowchart** that gives an overview of the CSHL historical collections and allows you to browse systematically;
1. you can view a set of **themes** that reflect important cross-cutting strengths of the collection; and
1. you can do text **searches** of the guide (and, if desired, the full catalog of CSHL finding aids and digitized material).

This guide illustrates the breadth and depth of the collection. It is intended not only for historians and scientists, but also for teachers and students at the high-school level and above, and cultural practitioners such as filmmakers, writers, and artists who engage with the role of biomedicine in public life. The guide is designed to complement two other important groups of resources: the CSHL Archives finding aids that offer a comprehensive listing of items in the collection, and existing writings on the history of biology in general and of the lab in particular, such as Jan A. Witkowski’s 2016 book The Road to Discovery: A Short History of Cold Spring Harbor Laboratory. We hope this new resource will inspire prospective researchers to use the finding aids, visit the collections (online and in person), and eventually make new contributions to our understanding of science and society.

## Archives Right Sidebar (1/3 column)
See Archives Right Sidebar

### Notable Collaborations (continuing on the right sidbar) 
These two square graphics should be stacked vertically and should link to the BGI and Genetech pages respectively. Graphics are at:  https://cshl.smugmug.com/2020-Archives-Website/n-jG9k4W/
- BGI Nobel Laureates Archives [BGI-Collections.png]
- Genentech Center for the History of Molecular Biology and Biotechnology  [Genentech-Collections.png]

## Highlights from the Archives (full column)
Four boxes with pictures of the 4 highlighted individual collections. There will be short descriptive text for each item (possibly as a flip box.):
- Alfred D. Hersey Collection
- Barbara McClintock Collection
- Hermann J. Muller Collection
- Amos G. Avery Collection

**Comment by srunkows** [comment]
This page has been built and is ready for review. The notable collaborations images in the sidebar are kind of large, have a look and see what you think. Also, I wasn't sure where to link the BGI image to.

https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-the-cshl-historical-collections/

**Comment by tomadams** [comment]
Those BGI and Genentech graphics do look large. Can you scale it to 60%?

The BGI image will link to the page describe in issue #58

**Comment by srunkows** [comment]
> Those BGI and Genentech graphics do look large. Can you scale it to 60%?
> 
> The BGI image will link to the page describe in issue #58

thanks, I must have missed that BGI link.

I added the link and scaled the images to 50 percent. We don't currently have a css style for 60% but I can always add one to the style sheet if you think 50% is too small.

**Comment by tomadams** [comment]
We can keep 50%.

1. Update the right sidebar as per: #45 
2. The row of images at the bottom page. Please change "Highlights from the Archives" to "Highlights from the Collections"
3. Remove line spacing before bullet points
4. Since we are no longer calling anything Flowchart, the bullet points need to be update.
5. At some point in time, there might be a Flowchart graphic, that will get added  to the text. But I have nothing for now.


- you can begin with the COLLECTIONS [link to collections] page that gives an overview of the CSHL historical collections and allows you to browse systematically;
- you can view a set of THEMES [link to themes] that reflect important cross-cutting strengths of the collection; and
- you can do text SEARCH WEBSITE [link to website search] of The Guide [link to https://archivesspace.cshl.edu/search?reset=true ] or the SEARCH FINDING AID.

Might use BLUE text for the above link, so they match the color on the right sidebar.

**Comment by srunkows** [comment]
> * The row of images at the bottom page. Please change "Highlights from the Archives" to "Highlights from the Collections"
> * Remove line spacing before bullet points
> * Since we are no longer calling anything Flowchart, the bullet points need to be update.

These changes are done.
Sidebar has not been updated yet.

**Comment by tomadams** [comment]
Oops. The link should be on the "SEARCH FINDING AID".
- you can do text SEARCH WEBSITE [link to website search] of The Guide or the SEARCH FINDING AID [link to https://archivesspace.cshl.edu/search?reset=true ] .

**Comment by srunkows** [comment]
> Oops. The link should be on the "SEARCH FINDING AID".
> 
> * you can do text SEARCH WEBSITE [link to website search] of The Guide or the SEARCH FINDING AID [link to https://archivesspace.cshl.edu/search?reset=true ] .

thanks for the clarification. I moved the link to the appropriate text

**Comment by srunkows** [comment]
sidebar updated and ready for review. https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-the-cshl-historical-collections/

**Comment by tomadams** [comment]
I made some typos on the: https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-the-cshl-historical-collections/ page.
- In the first card under Highlights from the collection, please change Hersey to Hershey
- Please rephrase:
 you can do text Search Website of The Guide or the Search Finding Aid.
 to: 
 you can perform a full-text search of _The Guide_ and this website using [SEARCH WEBSITE](https://lib-review-cshl-core.pantheonsite.io/search-cshl/) or the Finding Aids using [SEARCH FINDING AIDS](https://archivesspace.cshl.edu/search?reset=true).
- Please also ALL CAPS the "THEMES" and "COLLECTIONS" on links above.

**Comment by srunkows** [comment]
These updates are done.

The links have not been made into all caps. That is not an approved style on the website. All caps are used on buttons not inline text.

**Comment by tomadams** [comment]
Great.
