### ISSUE TITLE
Archives Right Sidebar

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#45]
Solid blue buttons (1/3 column wide)
 THEMES
 COLLECTIONS
 SEARCH

 CSHL ARCHIVES
 CENTER FOR HUMANITIES

For the COLLECTIONS FLOWCHART please have the URL as "collections" and not "collections-flowchart"

**Comment by tomadams** [comment]
There is a desire to tag the archival pages (with the exception of the main archives web page and any Center for Humanities pages) with "The Guide". It seems the best way to do this is within to with the Archives Right Sidebar. Thus all of the pages, with the exceptions listed above, need to have a right sidebar. For the Personal and Institutional Collections, this sidebar will actually appear below the "Avery Collection" and "Related Themes" sections.

One third of the page for the right sidebar, is looking a little excessive. Currently the right sidebar is col-lg-3. Can this be changed to col-lg-2, with the initial column bump up by one.

Change the right sidebar text to:

### _The Guide_
THEMES
COLLECTIONS
SEARCH WEBSITE
SEARCH FINDING AIDS (Goes to https://archivesspace.cshl.edu/search?reset=true  )
CONTACT AN ARCHIVIST

BTW
- Link "The Guide" to archives/guide-to-the-cshl-historical-collections/
- Can you give "The Guide", a cursive font, so that it appears to be an entity. Otherwise italics. To make it a little bigger, place in a h3 instead of a h4. Any other header section on the right hand side can remain h4
- Increase the FONT size within the button to 17, so that is more legible. Button remains same size.
- The CSHL ARCHIVES and CENTER FOR HUMANITIES buttons are to be removed.
- CONTACT AN ARCHIVIST should be btn-ghost.

Here is an example of what it might look like. Note I also eliminated the 50% scaling of the BGI/Genentech icon, otherwise the icons were unreadable when placed within a two column width. The last button should be "CONTACT AN ARCHIVIST"
![image](https://user-images.githubusercontent.com/1951133/100887471-038f1180-3483-11eb-87fc-9c4f0448647f.png)

**Comment by srunkows** [comment]
This change is going to require an update to the template code. The template does not currently have a field to put a heading above the blue buttons on the sidebar. So I will need to add this new filed to the database and template code.

Before I make the change to the column size, I want you to see what it will look like when I change the size on the sidebar column for large screens. 

I've attached 3 screen captures.
1) a large screen with col-lg-2 setting
2) a large screen with current column setting of col-lg-3 
3) a medium screen with current column setting of col-md-4
4) a medium screen with col-md-3 setting

Please let me know if you still want me to change the column size for large screens and if you want me to change the column size on medium screens. I only want to have to change the template once. Thanks!
[4-screencapture-medium-screen-col-md-3.pdf](https://github.com/tomadams/web2020/files/5632008/4-screencapture-medium-screen-col-md-3.pdf)
[3-screencapture-medium-screen-col-md-4.pdf](https://github.com/tomadams/web2020/files/5632009/3-screencapture-medium-screen-col-md-4.pdf)
[2-screencapture-large-screen-col-lg-3.pdf](https://github.com/tomadams/web2020/files/5632011/2-screencapture-large-screen-col-lg-3.pdf)
[1-screencapture-large-screen-col-lg-2.pdf](https://github.com/tomadams/web2020/files/5632012/1-screencapture-large-screen-col-lg-2.pdf)

**Comment by tomadams** [comment]
I am not sure what the screen captures are showing, other then to say the button are too long in 2 & 3. Would need to resize the screen width myself to get a feeling of what happens. Would also want to see it with the updated text.

Instead of placing "The Guide" at the top of the buttons, would the following issue #62  be possible instead?

**Comment by srunkows** [comment]
> Instead of placing "The Guide" at the top of the buttons, would the following issue #62 be possible instead?

see my reply in issue #62

**Comment by srunkows** [comment]
The Archives sidebar buttons have been added to all the personal collection detail pages. In addition, I created a new field in the sidebar that will allow you to brand certain personal collection detail pages with "The Guide". You can basically put anything you want in the field.

Have a look at https://lib-review-cshl-core.pantheonsite.io/personal-collections/amos-g-avery/

I put several different options, a heading that says "The Guide" which when clicked goes to The Guide to Historical Collections page, I put a sample image that when clicked goes to the guide to historical pages. You have the ability to put whatever you want as the heading, it is a WYSIWYG editor.

**Comment by tomadams** [comment]
Most Excellent.

For the individual and institutional collection pages, can you place it in this order: 
1. Avery Collection
2. Related Themes
3. The Guide (text only hyperlink) (will eventually graphic next week.)
4. Blue buttons
5. Availability of Materials
6. DHP Program Box

**Comment by srunkows** [comment]
> 1. Avery Collection

I assume you don't want 'Avery Collection' on all the pages and that it will change based on what page you're actually looking at.

**Comment by srunkows** [comment]
This reordering requires another change to the template code. You asked for 'The Guide' to be first so I wrote the code to display it first. Now you want it 3rd. I also will have to change the code to display the Related Theme section as well.

Please confirm that this is the final order for the sidebar content for all the Personal Collection pages. The final order will be used on all the collection pages. Individual pages cannot have custom ordering in the sidebar.  

I will change the template code one more time to match the final order for the sidebar. If you make a change again after this, it will have to wait until after site launch.

**Comment by tomadams** [comment]
I am confirming that this is the order desired for all of the Personal and Institutional Collection pages. To clarify:
- Avery collection title only appears on the Avery example; it will change based upon what collection we are looking at.
- Related Themes appear next. If there are no related themes, then the "Relate Themes" title will not appear.
- Related Resources. Additional area for links. Will not appear if empty. (We had used this section in the Biotechnology theme, might was well specify it here as well.)
- "The Guide" graphic will appear with link to the guide. (Will send you an updated png/svg). Set to width="100%", to match the length of the rest of the buttons.
- Blue buttons (Please increase the font size within the blue buttons. Make sure it does not get smaller on smaller devices.)
- Availability of Materials
- Box area. Can include the DHP Program, NRPHC Program, or any other graphic.

Here is an example (with an empty related resources but with the optional related themes):
![image](https://user-images.githubusercontent.com/1951133/101510710-43a13900-3948-11eb-8730-75e82e6617cb.png)

BTW - Can you share with me what the template fields are for the right sidebar. Does each section have it's own field, or is there  one big rich text field that you can place anything your want and in any order. It would help me understand what might need a template change and what might not. Or maybe there is not a right sidebar template and only a template for the entire page.

**Comment by tomadams** [comment]
"The Guide" graphic just emailed.

**Comment by srunkows** [comment]
The Personal Collections sidebar template has the following fields that are displayed in the following order (before I update the sidebar template with your new order):

1. Collection links header e.g. Avery Collection
2. Collection links - these links can be a link to another archive page, a related link (link external to the website, such as an Oral History page, finding aid, etc.), a PDF, or an image

3. Sidebar Blue/Ghost buttons widget

4. 'Other' Links header
5. 'Other' links - these links can be a link to another archive page, a related link (link external to the website, such as an Oral History page, finding aid, etc.), a PDF, or an image
I have not used the Other Links fields

6. Free Content Area - a WYSIWYG field that can contain anything
I have been using this field to add Related Themes content, Availability of Materials content, and Grant logos and text content

Archive pages that have a sidebar, such as Guide to Historical Collections, https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-the-cshl-historical-collections/ have the following fields that are displayed in the following order:

1. Sidebar Blue/Ghost buttons widget
2. Free Content Area - a WYSIWYG field that can contain anything
on the Guide to Historical Collections page, the Notable Collaborations header and BGI and Genentech images are placed in this field

**Comment by tomadams** [comment]
Thanks for the explanation.

Newly updated "The Guide" graphic just emailed.

**Comment by srunkows** [comment]
Here's Amos Avery's Personal Collection page with updated sidebar for review:

https://lib-review-cshl-core.pantheonsite.io/personal-collections/amos-g-avery/

**Comment by tomadams** [comment]
The page is looking very nice.

For all sidebars, let's user the headers:
-Avery Collection or  CSHL Symposia Collection (On the individual Personal/Institutional pages).  Where the phrase before "Collection" is the collection name or abbreviation of the name.  
-Relevant collections (On the individual theme pages)
-Relevant themes (On the individual personal / institutional pages.)

We, however,  will still keep "Related resources", which can go below the main body of the main text (and not in the sidebar).

Specifically for the Avery page, please have:
### Avery Collections
Existing links... 
### Relevant themes
Visual records and material culture ==> ???
Note that there is no "Related resource" for the Avery page, so that title and link should be hidden. (But it may appear in other pages.)

Were you able to do anything about, increase the FONT size within the button, so that is more legible. Button remains same size, by decreasing the top and bottom padding, to account for the slightly larger font.
![image](https://user-images.githubusercontent.com/1951133/101780141-22fdee00-3ac4-11eb-88a8-3679a8c09ca1.png)

**Comment by tomadams** [comment]
On the https://lib-review-cshl-core.pantheonsite.io/personal-collections/amos-g-avery/ page please change back "Relevant Collection" to "Avery Collection".  When I had previously stated that "Related Collection" should be "Relevant Collection", I was only referring to the Theme pages, not the collection pages.

**Comment by srunkows** [comment]
> On the https://lib-review-cshl-core.pantheonsite.io/personal-collections/amos-g-avery/ page please change back "Relevant Collection" to "Avery Collection". When I had previously stated that "Related Collection" should be "Relevant Collection", I was only referring to the Theme pages, not the collection pages.

done.

**Comment by tomadams** [comment]
Done.
