### ISSUE TITLE
Archives - Personal Collections

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#46]
The current page for Personal Collection: https://lib-review-cshl-core.pantheonsite.io/archives/personal-collections/
contains the individual's photo and name. Please include the brief description given below, within the photo/name box. Since this will make the page on the long side, we might want to consider an alphabet link or a name link to an anchor for quick access. 

The URL for the Finding Aids (etc) will go on the individual collection pages and not the top level personal collection page. These are additional URL, most of the individual person collections already have URLs.

## Personal collections
 ^ signifies that a collection features in the Genentech Center for the History of Molecular Biology and Biotechnology
 * signifies that a collection features in the BGI Nobel Laureates Archives

### Amos G. Avery photographic collection AGA
Selection of photographs from 1926 to 1942, the majority dating from the 1930s. The photos belonged to Amos G. Avery, who was an associate in plant breeding for the Carnegie Institution of Washington Department of Genetics at Cold Spring Harbor, managing the gardens and greenhouses under Dr. Albert Blakeslee from 1926-42. 

### Dr. Alan W. Bernheimer Sr. collection of Cold Spring Harbor Materials AWB
Materials related to the village of Cold Spring Harbor, 1897-1947, accrued by Bernheimer while on staff at the Biological Laboratory at CSH. This collection includes reprints, inventories, pamphlets, announcements, topographical maps and annual reports of the Cold Spring Harbor Whaling Museum.

Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/76

### *^Sydney Brenner collection SB
Immensely significant collection of over three hundred manuscript boxes of material documenting the life of molecular biologist Sydney Brenner and his colleagues. Coverage includes Brenner’s early years as a student in South Africa, his Nobel-prizewinning work as a scientist and administrator in Cambridge, UK from 1956-1995, and his zeal for biotechnology. The collection also includes material that belonged to Francis Crick and Leslie Barnett. 

### Clarence G. Campbell collection CGC
Campbell was a wealthy New Yorker who served as officer of several eugenics organizations. Dating from 1921 to 1938, this collection contains Campbell’s correspondence, manuscripts, clippings, reprints, published journals, lecture notes, and speeches/addresses. His career as eugenicist, scientist, and writer are well documented.
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/1

### ^Elof Carlson collection EAC
Personal and professional material accrued by geneticist and historian of genetics E.A. Carlson, primarily during his professional academic career from 1958-2000. The collection includes course notebooks, lecture notes and teaching files, scientific papers, correspondence, photographs, memorabilia, clippings, and material related to Carlson’s biography of H.J. Muller.

### *Francis H.C. Crick collection [a sub-collection of the SB personal collection]
This substantial sub-collection of the Sydney Brenner collection contains material that belonged to Nobel laureate Francis Crick, with whom Brenner had shared an office. When Crick left the MRC laboratory at Cambridge, Brenner preserved these materials, which include correspondence, photographs, scientific notes, and manuscripts by Crick and others.
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/archival_objects/45594

### Charles B. Davenport collection CBD
Papers and photographs from Davenport and his wife, Gertrude Crotty Davenport. Charles Davenport was the longtime director of several scientific institutions in Cold Spring Harbor, including the Biological Laboratory, the Station for Experimental Evolution, and the Eugenics Record Office. This collection includes biographical material, memorabilia, correspondence, photocopies of his articles, and family, institutional, and scientific photographs. Researchers interested in Davenport’s activities should also consult the relevant institutional collections at CSHL. 

### Dr. Charles DeLisi collection CDL
Letters related to the workshop “Sequencing the Human Genome,” which was organized by the US Department of Energy’s Office of Health and Environmental Research and held in Santa Fe, New Mexico, March 3-4, 1986.  Along with another workshop held two months later at CSHL, this event played an important role in building momentum toward initiating a human genome project.

### Hugo Fricke collection HF
Scientific notes, correspondence, and other material mostly dating to 1955-1972, when Fricke worked at Argonne National Laboratory, though the collection also includes material from Fricke’s years at CSH in the 1920s and 1930s. 

### Errol C. Friedberg collection ECF
Consists of material related to the research, writing, and publication of two biographies: The Writing Life of James D. Watson and Sydney Brenner: A Biography (both published by CSH Press), including transcripts of interviews with scientists and correspondence with scientists and publishers.

### James I. Garrels Protein Databases, Inc. collection JIG
These papers consist primarily of printed materials including newspaper clippings, annual report selections, and information related to the formation of Protein Database, Inc., a biotechnology company established in 1984 by Robert Franza and Jim Garrels of CSHL. 
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/21

### *^Walter Gilbert collection WAG
Includes material accrued by Gilbert as a student (Sidwell Friends School, Harvard University, Cambridge University), professor (Harvard University), and pioneering entrepreneur in the field of biotechnology (Biogen). The collection includes course notebooks, lecture notes and teaching files, scientific papers, correspondence, photographs, memorabilia, clippings, and material related to receiving the Nobel Prize.

### *Dr. Carol Greider collection CWG
Includes lab notes, correspondence, manuscripts, and visual material accrued by Greider during her postdoctoral work at the University of California, Berkeley from 1984-1987, and her early work at Cold Spring Harbor Laboratory from 1987-1992. Most materials are directly related to her work (with mentor Elizabeth Blackburn) on telomeres and telomerase, which would lead to the award of the Nobel Prize in Physiology or Medicine in 2009.

### Reginald G. Harris collection RGH
Extremely diverse collection, ranging from expedition notes and photographs from South America and Africa through to material about the administration of the laboratory, which Harris directed from 1924 until his death in 1936.

### Winship Herr collection WRH
Consists mainly of research-related material generated from 1991 to 1994, including laboratory notebooks, manuscript reviews, and letters requesting samples of plasmid from the Herr laboratory. 

### *Alfred Day Hershey collection ADH
Significant collection of personal and professional material belonging to Hershey, the longtime CSHL researcher and administrator and 1969 Nobel laureate. Notable contents include the blender used in the famous Hershey-Chase experiment, correspondence from throughout Hershey’s career, scrapbooks chronicling Hershey’s career and travels, and a trove of letters between Hershey and Harriet Jill Davidson from before their marriage

### James Hicks collection JH
The collection consists of laboratory research notebooks, one of which includes slide transparencies and photographs. One notebook was created by a student, Ramona Morfeld, who participated in CSHL’s Undergraduate Research Program (URP) in 1984. Another notebook is a manual for the Delbrück Laboratory. 

### Dr. Yuzuru Husimi collection YH
Contains reprints and patent applications related to Husimi’s work on the Human Genome Project.
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/80

### Dr. Hideki Kambara collection HK
This collection contains eight notable reprints of Kambara’s work and copies of eight patents directly related to his research.
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/69

### Amar Klar collection AJSK
Documents the research of Amar J. S. Klar during his time at CSHL (1978-1988), where he worked in the Yeast Group with Jeff Strathern and Jim Hicks at Delbrück Laboratory. The collection consists of laboratory research notebooks and a very small number of photographs and correspondence included in the first notebook.

**The following descriptions will be shortened, to be more uniform with the above.**

### Roberto Malinow Laboratory collection RM
Includes laboratory files, notebooks, administrative records, glass laboratory slides, magnetic data tapes, CD-ROMs containing data and photographs of experiment results. Many of the CD-ROMs contain unreadable files, as do all of the magnetic data tapes. 

### *Barbara McClintock collection BMC
Includes over 120 photographs, a correspondence file of 58 letters written and received by such notables as Charles Davenport, Milislav Demerec and Vannevar Bush, a set of 147 reprints written by 336 scientists and collected by Dr. McClintock, who made handwritten notations on them, and a slide collection consisting of 24 undated boxes of assorted sizes, which contain film of seedlings, kernels, and maize with Dr. McClintock’s notations on the boxes. The collection also includes actual corn kernels and photocopies of Dr. McClintock’s field notebooks card files. [Correspondence and images have been digitized and are online]

### *^Herman J. Muller collection HJM
The collection spans Muller’s entire life. Series include correspondence, biographical material and memorabilia, research and publications, and photographs. His correspondence is mainly professional and the bulk of it is with his friend and colleague, Edgar Altenburg, and with Elof Carlson. The biographical material primarily consists of autobiographies, items taken from Muller's office at Indiana University upon his death, and obituary articles. The research and publications consist of lectures, photocopies of articles, scientific notes, reprints, audio tape of lectures, and manuscripts of articles (some eventually published, some unpublished). Of particular interest is a letter H.J. Muller wrote to Stalin in 1936 which precipitated his exit from the USSR. Also of note is a large manuscript Muller had been working on for Erwin Baur about the history of Drosophila studies. The manuscript was left incomplete upon the death of Erwin Baur. The photographs in this collection are primarily those used by Elof Carlson for his biography of Muller but also include unlabelled family photographs of unknown origin. 

### Sir Kenneth Murray and Lady Noreen Parker Murray collection KMNPM
Contains documents pertinent to the EMBO Workshop on DNA Restriction and Modification in Basel, Switzerland during September 1972, and a laboratory notebook used by Sir Kenneth Murray in 1978 while at the University of Edinburgh. Within this notebook is a copy of a reprint by Peter Hans Hofschneider and Kenneth Murray, in 2001. 
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/73

### Dr. Gerald Rubin collection: Model organism genome sequencing, 1992-1999 GR
This collection is related to the development of a catalog for the Human Genome Project Archives. Of historical value is one of the three original signed documents dated January 1999 with Celera Genomics that spelled out the terms for the collaboration on the Drosophila genome sequencing project, signed by Craig Venter, founder of Celera Genomics in 1998, Gerald Rubin, and an official of the University of California at Berkeley. There also includes a folder on including emails and letters that deals with the Department of Energy’s consideration in 1992 of supporting model organisms sequencing. The question raised of whether is would be best to sequence worms or flies. There are letters from future Nobelists Robert Waterson and John Sulston praising the superiority of worms, and opposing views from Jasper Rine and Gerald Rubin promoting flies as the ideal model organism. Included are views from other scientists including Raymond Gesteland, and Lloyd Smith are included on this topic. There is also correspondence on DOE/NIH relations relevant to the Drosophila mapping project. 
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/70
Oral History ==> http://library.cshl.edu/oralhistory/speaker/gerald-rubin/

### Mark Ptashne collection MSP
The Mark Ptashne Collection consists of newspaper clippings, scientific correspondence (both original and photocopies) with 148 scientists including Nobel prize winners Francis Crick, Walter Gilbert, and Sydney Brenner. Much of the scientific correspondence is of a scientific nature mixed with personal exchanges. There is also special correspondence with Dr. George Klein and Charles M. Fair on shared interests such as art, music, science and philosophy. Material also includes emails, faxes, grant applications, patents both US and international, photographs, clippings, essays, awards, reports, and publications. The topics discussed range from scientific ethics, scientific fraud, the HIV/AIDS debate, Lasker award, discussions of scientific research, testimony of the Recombinant DNA Cambridge City Council Hearings, and the Cultural Congress held in Havana January -12, 1968, which brought together over four hundred "intellectuals" from the industrialized and third world nations to consider their role in the context of the revolutionary struggle in this era. Topics also include Mark Ptashne’s books “A Genetic Switch” and “Genes and Signals.” There are also grant applications and patents related to interferon.

Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/88

### Bruce W. Stillman collection BWS
A collection of scientific, administrative and personal materials of CSHL President and Chief Executive Officer, biochemist, and cancer researcher Bruce W. Stillman. The collection is largely composed of administrative papers, the scientific research/experiments done in Dr. Stillman’s Laboratory, and limited personal materials. 
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/79
Oral History ==> http://library.cshl.edu/oralhistory/speaker/bruce-stillman/

### Jeffrey Strathern collection JNS
The collection documents the research of Dr. Jeffrey N. Strathern. It is focused on his time at Cold Spring Harbor Laboratory (1977-1984), where he worked with Amar Klar and Jim Hicks at Delbruck Laboratory in the Yeast Group. The collection consists of laboratory research notebooks which include polaroid photographs and audiographs.

### Raquel Rotman Sussman collection RRS [Not digitized]
This collection consists of correspondence, notably with future Nobelist Alfred Day Hershey, subject files, laboratory notebooks spanning a 40 year period, a few photographs of herself with friends, and a set of her reprints including a reprint with Francois Jacob and Jacques Monod while she was at the Institute Pasteur in the 1960s.
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/62

### Akiyoshi Wada collection AW
This collection encompasses eight files and a binder of 24 CD-ROMs related to the completion of the human genome project. The files all relate to the Japanese human genome project including workshops, correspondence with Renato Dulbecco, reprints and photographs. 
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/68

### ^Bruce Wallace
[personal library with marginalia]
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/91

### Kitty Brehme Warren scrapbook collection [no call number]
The scrapbooks Kitty Brehme Warren maintaned are a primarily visual record of life at the laboratory from 1926 through 1950. Included in these two volumes are many photographs of lab personnel and visitors, the buildings and grounds, and both research-related and recreational events. Several symposium programs and clippings are also included. Dr. Brehme Warren's detailed notations and identifications are reproduced in the index. 

### *James D. Watson collection JDW
An extensive collection of scientific and personal materials of CSHL leader and Nobel laureate James D. Watson (CSHL Director 1968-1994, CSHL President 1994-2003, CSHL Chancellor 2003-2007, CSHL Chancellor Emeritus 2007-2014). In 2001, Watson donated the majority of his personal and scientific papers to the Cold Spring Harbor Laboratory Archives. As an active writer and outspoken scientist, Watson continues to receive correspondence, produce manuscripts and other historic materials, and to donate these materials to the archives. The collection at Cold Spring Harbor Laboratory contains: scientific and personal correspondence, manuscripts and typescripts, teaching files and administrative files (Harvard, CSHL, Human Genome Project), financial records, laboratory notebooks, scientific reprints, photographs, personal gifts, and memorabilia. 

### James D. Watson family collection JDWF
Consists of material that was created by the Watson family during the 19th century and the first half of the 20th century. The collection includes correspondence, writings, clippings, travel ephemera, and birding material. Additionally, the collection includes a series of genealogical research collected by the Watson family and by Watson’s archivists at Cold Spring Harbor Laboratory.
Finding Aid ==> https://archivesspace.cshl.edu/repositories/2/resources/77

### ^Charles Weissmann Biogen collection CWB
Consists of material accrued by Weissmann during his affiliation with Biogen, located in Geneva, Switzerland and Cambridge, MA. The collection includes Biogen corporate documents and correspondence, Biogen financial information both about the company and its primary shareholders, product research and development, and a set of photographs. In addition, many of the files contain experiment result photographs. The product development and research focuses on research and genetically engineered interferons (IFN) and interleukin 2 (IL-2). Biogen, one of the first biotechnology companies, was founded in 1978 in Geneva by several biologists, including Phillip Sharp of the Massachusetts Institute of Technology and Walter Gilbert of Harvard (who served as CEO during the start-up phase). 

### Evelyn Witkin collection EMW
Correspondence, historical material related to discovery of the SOS response in bacteria, and reprints. 

### ^Charles Yanofsky collection CY
Composed of professional and academic related material accrued or produced by Dr. Yanofsky. As Dr. Yanofsky has spent most of his career at Stanford University, much of the material references his tenure as Chairman of the Microbiology Department. The collection includes publications, awards, correspondence, laboratory notebooks and photographs.

### ^Norton Zinder collection NDZ
Consists of material accrued by Zinder as a student (Columbia University, University of Wisconsin), Professor (Rockefeller University), and as a pioneering researcher in the field of molecular biology. The collection includes course notebooks, lecture notes and teaching files, scientific papers, correspondence, photographs, memorabilia, clippings, and material related to his fifty year career at Rockefeller University. Specifically, the Biographical series includes 5 boxes of his notes and correspondence while and undergraduate and graduate student; as well as his thesis draft, family speeches, and 1962- 1994 Rockefeller University photos. The Rockefeller University series includes 89 boxes of lab notebooks and slides, administrative correspondence, and an additional 42 boxes of reprints. The Cold Spring Harbor Laboratory series is composed of 7 boxes of Board of Director minutes, notes, correspondence, speeches, lecture notes, blueprints and memorabilia. The Governmental Activities series of 52 boxes includes National Academy of Science (NAS) activities, the Human Genome Project; testimony before various governmental entities, and unclassified armed forces documents from National Research Council Activities.

**Comment by srunkows** [comment]
Request for clarification (let's discuss on our phone call later today):
1) The titles on the personal collection pages are just the person's name, but you have provided what appear to be longer titles, for example Amos G. Avery page is titled Amos G. Avery, with the description listed here you gave a title of 'Amos G. Avery photographic collection AGA' Do you want me to change the title on each individuals page with the ones provided here.

2) The summary text is long. I will add it to each individuals page but I will need a shorter one to put in the Card box on the Personal Collections page. Although Wordpress does support excerpt, the component that makes up this landing page is a custom not supplied by the Wordpress codebase and does not use the Wordpress excerpt. Since the content in a Card can be from anywhere, the summary sentence or two needs to be manually added.

I updated Amos Avery so you can see what it looks like before I proceed with the others.
https://lib-review-cshl-core.pantheonsite.io/archives/personal-collections/
https://lib-review-cshl-core.pantheonsite.io/personal-collections/amos-g-avery/

**Comment by tomadams** [comment]
1. On the top-level personal collection page, only use the person's name. On the individual personal collection page, please use the full title of the collection, listed above.

2. On each of the individual collections (Personal, Institutional, etc) their will be a new section called "Related Themes". Within the themes there will be one or more photo/title box links to either directly to a Theme or a to a "Theme-Collection-Connector".

For the Amos Avery example, please update the text at: https://lib-review-cshl-core.pantheonsite.io/archives/personal-collections/
> Selection of photographs from 1926 to 1942, the majority dating from the 1930s. The photos belonged to Amos G. Avery, who was an associate in plant breeding for the Carnegie Institution of Washington Department of Genetics at Cold Spring Harbor, managing the gardens and greenhouses under Dr. Albert Blakeslee from 1926-42.

On the individual page for Amos, please remove the editorial comment:
> [No link to digital images on ArchivesSpace] 

Please add at the bottom:
### Related Themes
- Visual records and material culture [Photo Visual.jpg / title] link to Visual records theme.

**Comment by srunkows** [comment]
> Please include the brief description given below, within the photo/name box.

All the descriptions have been added to the Personal Collections landing page cards. Some were quite long so I didn't copy the entire description. Ready for review.

Some of the descriptions are still rather long. You may want to consider making them shorter.

**Comment by srunkows** [comment]
> Please add at the bottom:
> 
> ### Related Themes
> * Visual records and material culture [Photo Visual.jpg / title] link to Visual records theme.

I added this to the sidebar. This is ready for review.

**Comment by tomadams** [comment]
With regards to the Amos Avery example at: https://lib-review-cshl-core.pantheonsite.io/archives/personal-collections/
I was envisioning the "Related Themes" being at the bottom of the mail text flow, using the theme images/title cards.

However, I am warming up to your idea of placing only the title into the right sidebar. The item should link to the actual theme page (not the image icon). Is there a way to add "tooltips" to display over the title during mouse hover (before the link is clicked?) This way the link can be described a little before visiting the link.

**Comment by srunkows** [comment]
> I was envisioning the "Related Themes" being at the bottom of the mail text flow, using the theme images/title cards.

ok, I added it at the bottom so you can see it and compare it to the sidebar. This template does not have the cards component so the styling is going to be different. It has the image and text below as a heading.

> Is there a way to add "tooltips" to display over the title during mouse hover (before the link is clicked?) This way the link can be described a little before visiting the link.

Yes, there is a tooltip component. I added it to the link in the sidebar so you can see it in action.

> The item should link to the actual theme page (not the image icon).

I changed the link (in the sidebar) to be just a link instead of linking to the image. Since there's no page for that theme yet, it doesn't actually link to anything yet.

**Comment by tomadams** [comment]
Please add the following alphabet letters (as an index) to the bottom of the main description, so that people are able to quickly jump to a particular entry:
![image](https://user-images.githubusercontent.com/1951133/100788397-00444900-33e3-11eb-95b0-dd06719a5c23.png)
Does not need to be 5 lines long. An image should not be used, just a bunch of capital letters with links to anchors below.

**Comment by srunkows** [comment]
This is not a trivial task.

I need time to think about and develop code to automatically generate this. It would be a nightmare to manually have to keep it updated. I also think this is going to require another database update to choose a letter for each post. With the last database change I only added a field for the entire last name for alphabetizing the posts when displaying on About Personal Collections page.

Attached are 2 mockups. One where there are no spaces between the letters and one with spaces between the letters. Please let me know which style you like better.
[screencapture-personal-collections-without-spaces-between-letters.pdf](https://github.com/tomadams/web2020/files/5632305/screencapture-personal-collections-without-spaces-between-letters.pdf)
[screencapture-personal-collections-with-spaces-better-letters.pdf](https://github.com/tomadams/web2020/files/5632311/screencapture-personal-collections-with-spaces-better-letters.pdf)

**Comment by tomadams** [comment]
Just an idea - You might not have to develop additional code to create this block. It can be static, we would just need to update this index block **only** when a new letter is activated. I believe that most browsers will go to the first named anchor, so that you can place an anchor in front of every collection card based upon the first letter of the new sort field.

I am having a difficult time distinguishing between the active and inactive letters. Can you have the inactive letters have a lighter gray color (such as the example) , instead of black. Please also use the web-safe "Arial Black" font, for a fuller body typeface look.

When we add a right sidebar to this personal-collections page, I am thinking that this index will appear in the sidebar in the multi-row display as seen above. If you allow the text to flow, you might want A&nbsp;- 

It looks better "with spaces". I don't know if &bull; would look better than the hyphens.

**Comment by srunkows** [comment]
Indexing/filtering added and ready for review. https://lib-review-cshl-core.pantheonsite.io/archives/personal-collections/

**Comment by tomadams** [comment]
Like the functionality that when you click on a letter, you only get to see those collections. Much better than just jumping to that part of the page. Like that it defaults to "ALL".

Is there a way to hide or gray out the "E,I,J,L,N,O,Q,T,U,V,X" buttons, thus preventing the "No personal collections found" message?

Let's add the Archives sidebar only to the top of this page. Want to keep the bottom area that displays the different collections card at full width. 

I will provide you with a small icon, that can be used to identify is a collection is part of the BGI and/or Genentech collection. This can be added to the bottom of the short description (instead of at the beginning of the title.)

Can the index be placed in a 5 or 6 column grid? In trying to keep with the initial styling.

**Comment by srunkows** [comment]
> Is there a way to hide or gray out the "E,I,J,L,N,O,Q,T,U,V,X" buttons, thus preventing the "No personal collections found" message?

I'd have to write  code to do this. This will have to wait until after site launch.

>Let's add the Archives sidebar only to the top of this page. Want to keep the bottom area that displays the different collections card at full width.

This would be another code change to create a new template that has a half page height sidebar. This is going to have to wait until after site launch.

>Can the index be placed in a 5 or 6 column grid? In trying to keep with the initial styling.

Yes, but again it's another code change and will have to wait until after site launch.

**Comment by tomadams** [comment]
The end is near. Moved to the After Launch Milestone.

**Comment by tomadams** [comment]
Broke off the the Alphabet Index as separate issue. We will continue this top-level collection page for the release...

Please add the Archives Right Sidebar, which should be identical to what the non-collection pages have:
-[Last Name of Person, e.g.] Avery Collection
-Relevant Themes
- "The Guide" graphic will appear with link to the guide. Set to width="100%", to match the length of the rest of the buttons.
- Blue buttons (Please increase the font size within the blue buttons. Make sure it does not get smaller on smaller devices.)
- Availability of Materials
- Box area. Can include the DHP Program, NRPHC Program, or any other graphic.

Any "Related Resources" section, will appear below the main text column.

The https://lib-review-cshl-core.pantheonsite.io/personal-collections/amos-g-avery/ page right sidebar is close, except "Relevant Collections" header, should be "Avery Collection". Only when we are on the themes pages, will there be a "Relevant Collection" header.

**Comment by tomadams** [comment]
Avery looks good.
