### ISSUE TITLE
Archives - Themes - Biotechnology

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#48]
## BIOTECHNOLOGY

The CSHL archive is one of the world’s most significant repositories of primary material documenting the history of biotechnology. While reflecting CSHL’s own important place in the molecular revolution in biology, the collection is truly global in scope as a result of accessions from individuals and organizations who worked beyond Long Island. Important phases in the history of biotechnology are all well represented in the CSHL collection, including the origins of recombinant DNA research, practical and ethical debates over the safety of genetic modification of organisms, and legal proceedings over intellectual property rights to biological materials and methods.

Many of the personal collections deal extensively with biotechnology, including the extremely large Sydney Brenner and James D. Watson collections. Brenner was enthusiastic about biotechnology, as evidenced by many reports and talk-transcripts in which he assessed the state of the field (see, for example, his 1983 talk, “Overview of Biotechnology in Industry - Keynote Address, Seminar on Biotechnology – Singapore” SB/3/23). As director of CSHL and the early Human Genome Project, Watson was notably ambivalent about patenting of genes (see, for example, the letter from Watson to Herman Daly and Robert Goodland, 1992 JDW/2/2/2025/5), but he recognized that “we [i.e., CSHL] have no choice but to upgrade ourselves for the biotechnology world of the next century” (Watson to John A. Luke, 18 October 1989, Watson Collection, 3/7/3, box 3).

The centrality of intellectual-property controversies to the history of biotechnology is illuminated in an extraordinary collection of documents in the Brenner collection related to the lawsuit filed by Genentech, Inc. against Wellcome PLC in the United Kingdom for patent infringement of a drug known as “tPA.” Brenner was hired by Genentech to serve as an expert consultant and witness during the trial. The files include correspondence from Genentench, Inc. regarding hiring Brenner, legal filings (many with notes by Brenner), transcripts of the arguments, the decision, and supporting documents, and even a daily journal kept by Brenner during the trial (SB/4/3). [Additional correspondence related to the trial can be found in the Institutional Correspondence subseries (SB/1/2).]

Biotechnology and academic-commercial partnerships are discussed in many of the interviews in the Oral History collection (see, for example, interviews with Michael Ashburner, Hans Clevers, Ari Patrinos, and John Sulston), and the topic was also the inspiration for one of the CSHL History of Science meetings, 2008’s “Biotechnology: Past, Present, and Future.”

The archive also contains material that predates the term “biotechnology,” but deals with related themes of commercialization of research products. These can be found in records of CSHL’s precursor institutions held in the Brooklyn Institute of Arts and Sciences (1890-1941) collection and the Long Island Biological Association (1900-1962) collection. 

### Related resources:
Robert Wargas and Ludmila Pollock, 2013. “Second Century: Cold Spring Harbor Laboratory and the Biotechnology Revolution.” < http://library.cshl.edu/special-collections/142-library/static-library-homepage/393-second-century-cold-spring-harbor-laboratory-and-the-biotechnology-revolution >  
“The Human Genome Project: An Annotated & Interactive Scholarly Guide to the Project in the United States,” which can be viewed online: http://library.cshl.edu/Guide-to-HGP

### Relevant collections:
- Sydney Brenner collection
- Brooklyn Institute of Arts and Sciences (1890-1941) [for pre- “biotechnology” discussions of commercialization]
- CSHL [many sub-collections including:]
-- Office of Technology Transfer collection (1972-)
--	Documents related to the Cellbiology company (see e.g., CSHL Annual Report for 1981).

- Hugo Fricke collection
- James I. Garrels Protein Databases, Inc. collection
- Walter Gilbert collection
- History of Science meetings [2008 meeting, “Biotechnology: Past, Present, and Future.”]
- Dr. Yuzuru Husimi collection
- Long Island Biological Association (1900-1962) [for pre- “biotechnology” discussions of commercialization]
- Dr. Hideki Kambara collection
- Sir Kenneth Murray and Lady Noreen Parker Murray collection 
- Oral History collection
- Dr. Gerald Rubin collection: Model organism genome sequencing, 1992-1999
- Bruce W. Stillman collection
- Akiyoshi Wada collection
- James D. Watson collection
- Charles Weissmann Biogen collection
- Norton Zinder collection

{The all above will be a links, either directly to collection page, or to a connection page between the two.}

**Comment by tomadams** [comment]
Captions for Biotechnology and commercialization: 
1.	Walter Gilbert at a Biogen Meeting, 1981
2.	Charles Weissmann on the occasion of the interferon approval, Biogen, 1986
3.	Sydney Brenner and Nat Sternberg at Du Pont Company, 1990
4.	Broad Hollow Bioscience Park Ribbon Cutting, 2000
5.	Biotechnology at CSHL, 2013 paper by Robert Wargas

**Comment by srunkows** [comment]
I built a draft of this page to use as a starting point for designing it and all the other theme pages. I didn't want to build out the others until we decide on a layout. Also, in the interest of time, I did not add links to the Relevant collections. They will be added when we decide on the best layout for these pages.

https://lib-review-cshl-core.pantheonsite.io/archives/themes/biotechnology/

**Comment by tomadams** [comment]
Please look for my email on 11/19/2020 at 5:49PM Subject: Archives Website - Photos for the individual themes pages  -Biology and Biotechnology
That email contains the Biotechnology01-04 photos, which should have the captions listed above.
Please add those photos to the Biotechnology page.
You can add the pictures in-line to the text itself. If that does not work, try a row of images with captions at the top.

For the "Relevant collections" section,
I was expecting cards (image/title) of the collections, with anything within [ ... ] would be descriptive text.

**Comment by srunkows** [comment]
> Please look for my email on 11/19/2020 at 5:49PM Subject: Archives Website - Photos for the individual themes pages

ok, will do. Thanks!

**Comment by tomadams** [comment]
After seeing "Relevant collection" in both the right hand column and bottom of the page with page with pictures, the team decide to go with having the "Relevant collections" section to appear only on the right hand side, as it appears in the https://lib-review-cshl-core.pantheonsite.io/personal-collections/amos-g-avery/
The section at the bottom can be removed.

The team also wanted to see what it looked like if we added the updated "Archives Right Sidebar", Right above the "Avery Collection", on the right column.

**Comment by srunkows** [comment]
I removed the section and image at the bottom.

The template currently does not support adding content above the Collection content in the sidebar. This requires a change to the database and template code. Before I proceed I want you to approve the browser mockup to make sure this is really what you want.

In this instance, I don't recommend going to a smaller column width for large screens as there is so much text and content it drives the content down really far on the page. See the attached screen capture files. It is a large screen with the col-lg-2 setting and one with the current col-lg-3 setting.
[screencapture-large-screen-col-lg-2.pdf](https://github.com/tomadams/web2020/files/5632124/screencapture-large-screen-col-lg-2.pdf)
[screencapture-large-sreen-col-lg-3.pdf](https://github.com/tomadams/web2020/files/5632125/screencapture-large-sreen-col-lg-3.pdf)

**Comment by tomadams** [comment]
In this case, the col-lg-3 looks better. Maybe you can give me a call tomorrow and we can discuss the right sidebar -- before you make massive changes. 

Can you also change: "Amos Avery photographic collection processing" to the shorter "Processing of collection".

**Comment by srunkows** [comment]
> In this case, the col-lg-3 looks better. Maybe you can give me a call tomorrow and we can discuss the right sidebar -- before you make massive changes.

Sorry, I've been in meetings all morning and have more meetings this afternoon. Can we do a call on Friday afternoon?

**Comment by srunkows** [comment]
> Can you also change: "Amos Avery photographic collection processing" to the shorter "Processing of collection".

this is done

**Comment by tomadams** [comment]
Not sure if "Processing of collection" is proper English, can we go with:  "Processing of the collection".
Change the ghost button to: "CONTACT AN ARCHIVIST".

Talk with you tomorrow.

**Comment by srunkows** [comment]
I laid out the biotechnology page a little differently, using a sidebar and cards. I added 3 of the 4 photos (with captions). There wasn't quite enough text to fit all 4 photos without things getting jumbled on certain screen sizes. I can make the 4 photos into a slideshow instead, removing the 3 small photos. https://lib-review-cshl-core.pantheonsite.io/archives/themes/biotechnology/

**Comment by tomadams** [comment]
I thought we were going to keep the Related Connections on the right hand side https://github.com/tomadams/web2020/issues/48#issuecomment-736751806 and you had removed it from appearing the bottom.
> After seeing "Relevant collection" in both the right hand column and bottom of the page with page with pictures, the team decide to go with having the "Relevant collections" section to appear only on the right hand side

Any of the additional text would be placed in a tooltip.

Currently with the cards at the bottom, it appears too narrow.

With regards to 4 photo, let we what it looks like with your suggestion. Just make sure the captions still exist.

**Comment by srunkows** [comment]
I'm confused. I thought you said you wanted the bulleted list of the relevant collection turned into cards.

> For the "Relevant collections" section,
I was expecting cards (image/title) of the collections, with anything within [ ... ] would be descriptive text.

Also, there seem to be comments in this issue that are not related to the Biotechnology page and seem like they were meant more for the Avery Collection page which is where I put the example of the tooltip on the Related Themes item.

**Comment by tomadams** [comment]
Yes, initially I thought the relevant collection section would be cards at the bottom. Since then you showed me how nice the relevant themes section looking in the sidebar of Avery collection. It seemed natural to carry that same design to the individual theme pages as well. (Since relevant themes and relevant collections are symmetrical.) I know, bringing up the Avery collection in the thread, is just adding to the confusion.

The right sidebar for the themes page, is similar to the individual Personal and Institutional collections pages, but the top is slightly changed:
- Related Collections. [with links either directly going to a collection or a theme/collection connector page.] [Tooltip can be specified for entry.]
- Related Resources. Additional area for links. Will not appear if empty. (We had used this section in the Biotechnology theme.)
- "The Guide" graphic will appear with link to the guide. (Will send you an updated png/svg). Set to width="100%", to match the length of the rest of the buttons.
- Blue buttons (Please increase the font size within the blue buttons. Make sure it does not get smaller on smaller devices.)
- Availability of Materials
- Box area. Can include the DHP Program, NRPHC Program, or any other graphic. (for Biotechnology this will be empty.)

**Comment by srunkows** [comment]
ok, thanks for the clarification!

**Comment by srunkows** [comment]
ok, I took another stab at the layout for the Biotechnology theme page. I'm still missing some links for instance Brooklyn Institute of Arts and Sciences.

Have a look and let me know if this layout is better: https://lib-review-cshl-core.pantheonsite.io/archives/themes/biotechnology/

**Comment by tomadams** [comment]
Please also include "The Guide" button at the top of the blue buttons. You have moved the "Related Resources" to the bottom of the main text - it looks good there.

For all links in the "Relevant collections" section, please leave off the word "collection". So the first item would be "Sydney Brenner" and not "Sydney Brenner collection".

For the "missing" links:

Brooklyn Institute of Arts and Sciences ==> https://lib-review-cshl-core.pantheonsite.io/archives/institutional-collections/brooklyn-institute-of-arts-and-sciences/
with tooltip => pre- “biotechnology” discussions of commercialization

Cold Spring Harbor Laboratory ==> https://lib-review-cshl-core.pantheonsite.io/archives/institutional-collections/cold-spring-harbor-laboratory/
with tooltip ==> many sub-collections including: Office of Technology Transfer collection (1972-), Documents related to the Cellbiology company (see e.g., CSHL Annual Report for 1981).

Long Island Biological Association ==> https://lib-review-cshl-core.pantheonsite.io/archives/institutional-collections/long-island-biological-association/
with tooltip ==> for pre-“biotechnology” discussions of commercialization

Dr. Gerald Rubin ==> https://lib-review-cshl-core.pantheonsite.io/personal-collections/dr-gerald-rubin/
with tooltip:  Model organism genome sequencing, 1992-1999

**Comment by srunkows** [comment]
I think this page is now done and ready for review. I added the 4th image that was supplied, all the Relevant Collection items in the sidebar are now linked, and the Guide button has been added.

**Comment by tomadams** [comment]
Looks good. Thanks.
