### ISSUE TITLE
Archives - Theme - Biology and Medicine

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#49]
Research and discovery in
### Relevant Collections
- Sydney Brenner collection
- Elof Carlson collection
- Carnegie Institution of Washington at CSH administrative records (1898-1977) 
- CIW Eugenics Record Office collection
- Cold Spring Harbor Laboratory collection (1923-) CSHL
- Transcripts of CSHL meetings on history of science (2005-)
- CSHL Meetings and Courses department collection (1890-)
--   CSHL meetings abstracts collection (1966-2012)
- Hugo Fricke collection
- Walter Gilbert collection
- Dr. Carol Greider collection
- Reginald G. Harris collection
- Winship Herr collection
- James Hicks collection
- Amar Klar collection
- Long Island Biological Association (1900-1962)
- Roberto Malinow Laboratory collection
- Barbara McClintock collection
- Sir Kenneth Murray and Lady Noreen Parker Murray collection
- Raquel Rotman Sussman collection
- Bruce W. Stillman collection
- Jeffrey Strathern collection
- James D. Watson collection
- Evelyn Witkin collection
- Charles Yanofsky collection
- Norton Zinder collection

**Comment by tomadams** [comment]
Captions:
Research and Discovery in biology and medicine
1.	Richard J. Roberts, 1974
2.	Evelyn Witkin, 1958
3.	J. Potter, M. Findley, E.C. MacDowell & M. Taylor in the mouse genetics lab which they used to study human disease, 1930s
4.	Main Building, opening day, 1905

**Comment by srunkows** [comment]
A skeleton of this page ahas been created. There didn't seem to be any content other than relevant collections and photos.
I added the links in the sidebar, but not sure if you just want the content section to just be photos. Please let me know.

https://lib-review-cshl-core.pantheonsite.io/archives/themes/biology-and-medicine/

**Comment by tomadams** [comment]
Please add the following text and previously provided pictures with captions.

### Research and discovery in biology and medicine
 
From laboratory notebooks to letters exchanged between collaborators, from crystallography images to historic instruments, the CSHL collection contains an extraordinary wealth of material documenting the process of research and discovery across many eras of the history of biology and medicine.
 
The rich sources at CSHL show that scientific discovery is a complex process—with social as well as cognitive dimensions—that stretches far beyond any single “eureka!” moment. For example, the Carol Greider collection documents her Nobel Prize-winning research on telomerase across a wide range of activities over the course of more than a decade: [lab assays](https://cshl.smugmug.com/Carol-Greider-Archives/CWG-01-001/i-3XRww8S/A) and [diagrams of enzyme activity](https://cshl.smugmug.com/Carol-Greider-Archives/CWG-01-001/i-GHb69Nf/A) recorded in [notebooks](https://archivesspace.cshl.edu/repositories/2/archival_objects/73463) dating to her graduate studies at Berkeley; [discussions of how authorial credit should be allocated among collaborators](https://cshl.smugmug.com/Carol-Greider-Archives/CWG-01-22/i-snN98Cv/A); struggles with [recalcitrant peer reviewers and concerns about being “scooped;”](https://cshl.smugmug.com/Carol-Greider-Archives/CWG-01-22/i-6wSZgS8/A) and [reactions to seeing the research discussed in the popular press](https://cshl.smugmug.com/Carol-Greider-Archives/CWG-01-22/i-QcbHNRK/A). And as with many other topics, the breadth of CSHL’s collections offers perspectives on Greider’s telomere research beyond those found in her own records: from an [oral history interview](https://library.cshl.edu/oralhistory/speaker/elizabeth-blackburn/) with her doctoral supervisor and co-laureate Elizabeth Blackburn to administrative documents about her tenure as a postdoctoral fellow and investigator at CSHL (these and other personnel records are subject to embargo for privacy reasons, but have been preserved for future generations of researchers).
 
In keeping with CSHL’s tradition of hosting scientific meetings and courses, the collection is particularly strong in documenting how collaborations were fostered and research results were disseminated and discussed. The archive holds programs, abstracts, photographs, and memorabilia from CSHL symposia and other meetings; the CSHL library holds published materials that emerged from those meetings, including the annual Symposium volumes; the oral history collection includes interviews with hundreds of organizers and attendees of CSHL meetings; and many of the personal collections include conference-talk drafts, meeting programs (from CSHL and elsewhere), and correspondence with collaborators.
 
In addition to paper records, the CSHL collections contain artifacts from some of the most consequential research programs in the history of biology, including maize kernels from Barbara McClintock’s discovery of transposable elements and the blender used in the 1952 Hershey-Chase experiment that helped to establish that genetic material is made of DNA rather than protein. (See also the theme Visual Records and Material Culture.)

**Comment by srunkows** [comment]
Text and photos added. https://lib-review-cshl-core.pantheonsite.io/archives/themes/biology-and-medicine/

**Comment by tomadams** [comment]
OK
