### ISSUE TITLE
Search Needs Filtering for Library and Archives

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#5]
When looking at the search results, there is no way to limit it to only Library or Archives.

**Comment by srunkows** [comment]
There are now separate topics for Library and CSHL Archives in the search. Still working on recategorizing the existing posts (will be finished this morning) but the filtering for the search is now working.

**Comment by srunkows** [comment]
This should be done now. The posts are recategorized and the separate filtering is available on the search results page. There is now a filter for Library and one for CSHL Archives.

I've also pushed this update to production.

**Comment by tomadams** [comment]
Within search, it appears that I am only able to select either Library OR Archives. Is there a way to view the combination of both of them together? It looks like the search filter only allows a radio button and not a checkbox.

**Comment by srunkows** [comment]
The search filters have been configured with radio buttons which means it only searches for Library or Archives. I'll investigate if checkboxes are available. It would be good to do compound searches within each filter. But this is something I will look into at a later date after all other issues have been addressed.

**Comment by srunkows** [comment]
I investigated the filtering options for the plugin that handles our faceted search. They do have an option for checkboxes as opposed to radio buttons. I have added this to my list of website improvements and will investigate the impact of implementing.

**Comment by srunkows** [comment]
tonight, I deployed the code to turn the Topic radio buttons into checkboxes. There is now a checkbox for Archives and a checkbox for Library. 

This is done and ready for review.

**Comment by tomadams** [comment]
Great
