### ISSUE TITLE
Archives - Theme - The Human Sciences

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#50]
Research and discovery in
## The Human Sciences

description here...

### Relevant Collections

- Eugenics material
-- Brooklyn Institute of Arts and Sciences (1890-1941)
-- Herman J. Muller collection
- Reginald G. Harris collection 
- Long Island Biological Association (1900-1962) 
- Norton Zinder collection

**Comment by tomadams** [comment]
Captions:
Research and discovery in the human sciences
1.	CSHL Symposium on Brains & Behavior: order and disorder in the nervous system, 2018
2.	Field workers training class, 1913
3.	Drosophila lab, 1930s
4.	Drosophila specimen in the lab, 1930s

**Comment by srunkows** [comment]
Skeleton of page has been built: https://lib-review-cshl-core.pantheonsite.io/archives/themes/the-human-sciences/

**Comment by tomadams** [comment]
Please add the following text and previously provided pictures with captions

### Research and discovery in the human sciences
 
Although CSHL is best known for research in biology and medicine, our collections hold material of considerable interest in connection with the history of the human sciences (such as anthropology and psychology) and their antecedent disciplines (such as ethnology). Some of this material was gathered in connection with studies of heredity in humans and other organisms, and (in the early twentieth century) especially because of its relevance for the theory and practice of eugenics
 
From 1910 to 1939, Cold Spring Harbor was the site of the Eugenics Record Office. Although many of the ERO records have been transferred elsewhere, the ERO collection in the CSHL archives contains historically significant material on the funding and administration of American eugenics and on the training of eugenics fieldworkers. CSHL’s rare books collection includes a wide range of eugenics manuals, pamphlets, and conference proceedings, as well as many works of late-nineteenth and early-twentieth century ethnology. There is additional material related to eugenics in the Charles B. Davenport and Herman J. Muller personal collections, the institutional collection of the Brooklyn Institute of Arts and Sciences, and the annual reports of CSHL’s various precursor institutions.
 
The Reginald G. Harris collection will be of particular interest to historians of the human sciences because it contains expedition notes and photographs from his travels in Central and South America and North Africa. Harris’s documentation of the Kuna people of Panama, including lantern slides and negatives and a sheet of pictographic writing, is particularly noteworthy. Harris’s [related publications](https://repository.cshl.edu/view/cshl_author/harris=5Freginald.html) in the American Journal of Physical Anthropology and elsewhere can be found in the CSHL Institutional Repository.

**Comment by srunkows** [comment]
Text and photos added. https://lib-review-cshl-core.pantheonsite.io/archives/themes/the-human-sciences/

The photos you sent for the human sciences seemed to be missing the 3rd photo, only 1,2, and 4 were sent. There's really not enough room to add another photo, have a look and let me know what you.

**Comment by tomadams** [comment]
Looks good. Done.
