### ISSUE TITLE
Archive - Theme - The Environmental Sciences

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#51]
Research and discovery in
## The Environmental Sciences

description here.

### Relevant Collections 
- Brooklyn Institute of Arts and Sciences (Field courses, etc.)
- Reginald G. Harris collection (Panama expedition; Cornell entomological expedition to South America)
- Bruce W. Stillman collection (New Zealand travel diary)
- James D. Watson family collection (JDW, Sr.’s birding records)
- Norton Zinder collection (chemical demilitarization)

**Comment by tomadams** [comment]
Captions:
Research and discovery in the environmental sciences
1.	First biolab class returning from a specimen trip, 1890
2.	First biolab class, 1890
3.	Breeding Room of the Main Building, 1906
4.	Barbara McClintock corn fields behind main building, ca. 1940s

**Comment by srunkows** [comment]
Skeleton page has been built: https://lib-review-cshl-core.pantheonsite.io/archives/themes/the-environmental-sciences/

**Comment by tomadams** [comment]
Please add the following text and the pictures with captions previously sent to the page.

### Research and discovery in the environmental sciences
The first scientific institutions at Cold Spring Harbor were established because the site offered favorable access to marine specimens from both fresh and salt water. Although the place is now better known for laboratory-based discoveries in molecular biology and genetics, CSHL’s historical collections hold a wide range of materials related to fieldwork conducted on Long Island and on expeditions around the world. Holdings from throughout the CSHL collections also shed light on related themes of ecology and environmentalism.
 
Records from the collection of the Brooklyn Institute of Arts and Sciences, which operated the first field station and summer school at Cold Spring Harbor, show just how significant field excursions and specimen collecting were to biological work of the time. Of particular interest is the 1898 “Biological Survey of Cold Spring Harbor and the adjacent regions,” which documented fauna from twenty-six dredging stations in addition to land- and stream-dwelling animals and plants.   
 
Highlights among the expeditionary records held in the CSHL collections include notes and artifacts from Reginald Harris’s participation in the 1919-1920 Cornell entomological expedition to South America and a diary and maps from one of Harris’s distant successors as a CSHL director, Bruce Stillman, on his 1977 travels in New Zealand. The Watson Family collection includes James Watson, Sr.’s bird-watching notes, which document an avocation that helped to spur his son’s enthusiasm for science.
 
The Norton Zinder collection offers rich insight into the history of late-twentieth century environmental thought through material related to his chairmanship of a National Academy of Sciences committee on chemical demilitarization.

**Comment by srunkows** [comment]
Text and photos added. https://lib-review-cshl-core.pantheonsite.io/archives/themes/the-environmental-sciences/
Photos emailed seemed to be missing photo #2, only got 1,3, and 4.

**Comment by tomadams** [comment]
Good.
