### ISSUE TITLE
Archives - Theme - Patronage and funding of research

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#52]
## Patronage and funding of research

description here.

### Relevant Collections
- Sydney Brenner collection
- Brooklyn Institute of Arts and Sciences (1890-1941)
- Carnegie Institution of Washington at CSH administrative records (1898-1977) 
- Cold Spring Harbor Laboratory collection (1923-) CSHL
- Dr. Charles DeLisi collection
- Relates to the 1986 DOE workshop in Santa Fe that helped to establish the HGP
- Hugo Fricke collection
- Winship Herr collection
- Alfred Day Hershey collection
- NIH grant applications
- Long Island Biological Association (1900-1962) 
- Financial statements, lists of funds, fund raising.
- Dr. Gerald Rubin collection: Model organism genome sequencing, 1992-1999
- Bruce W. Stillman collection
- James D. Watson collection
- Charles Weissmann Biogen collection
- Charles Yanofsky collection
- Norton Zinder collection

**Comment by tomadams** [comment]
Captions:
Patronage and funding of research
1.	Elizabeth Watson, Charles Robertson, James D. Watson, 1970
2.	Grace Auditorium, 1986
3.	Dolan Hall and Beckman Neuroscience Center, 1991
4.	BGI $5 Million Dollar Donation to CSHL Archives, 2019

**Comment by srunkows** [comment]
Skeleton page created: https://lib-review-cshl-core.pantheonsite.io/archives/themes/patronage-and-funding-of-research/

**Comment by srunkows** [comment]
> 1. Elizabeth Watson, Charles Robertson, James D. Watson, 1970

photo was missing from email, can you please resend.

**Comment by tomadams** [comment]
Ignore missing photo.

### Patronage and funding of research
 
Records of how funding was sought and achieved for scientific research, teaching, and institution building—at Cold Spring Harbor and elsewhere—often yield extraordinary historical insights. Patterns of funding can be revealing in themselves, such as by showing that various types of scientific research were sponsored by patrons ranging from individual citizens to government agencies, from private foundations to branches of the military. Beyond that, documents like grant proposals and letters of support often contain sentiments and details that would not otherwise be preserved in the historical record, for example about scientists’ intellectual ambitions and value judgments, or about the kinds of infrastructure and personnel that would be necessary to conduct a given kind of research. 
 
Among the documents in CSHL’s personal collections are many grant applications, fellowship proposals, and letters between scientists discussing funding. Information about planning and funding for the most ambitious life-sciences research initiative in history, the Human Genome Project, is well represented in the Charles DeLisi collection, the James D. Watson collection, and others, and is much discussed in the Oral History collection. On a more personal scale, the Alfred Day Hershey collection contains a decade’s worth of NIH grant applications and the Carol Greider collection includes, among many other relevant sources, a disappointed [exchange of letters](https://cshl.smugmug.com/Carol-Greider-Archives/CWG-01-22/i-fmSRcGB/A) between collaborators when one of their NIH applications was turned down.
 
The sometimes fraught history of efforts to finance the operations of CSHL itself (and its precursor institutions) is documented throughout the institutional collections, which contain a wealth of information about how funds were secured to support individual faculty members and particular research initiatives, building projects, and events. Annual budgets are a rich source of detail. For example, the 1960-1961 budget of what was then known as the Biological Laboratory (pp. 494-500 of the Minutes of the Board of Trustees, LIBA, 1933-1971; LIBA Collection) illustrates that research at the lab was funded by a series of grants from public and private sources (the US National Institutes of Health and National Science Foundation, the Josiah Macy, Jr. Foundation, the Atomic Energy Commission, and two children’s charities). Operational costs for the lab itself were funded almost entirely through a combination of profits from sales of the annual CSH Symposium volumes, fees charged for dining and rental of facilities, and “overhead” withheld from the aforementioned research grants. Meanwhile, a large construction and renovation project was being funded by an NSF grant for that purpose.
 
Tracing the same institutional records reveals that the laboratory’s capital expenses for the first nine months of that fiscal year far exceeded income, prompting a vigorous discussion about finances. Among the notable suggestions was one by Harold Abramson, proposed that “universities have obtained large returns from the patenting of results of research [and] this might be a way out of our difficulties.” It was twenty years before CSHL pursued the latter course (see the theme page on Biotechnology). Not revealed in these minutes was that the funds for Abramson’s own research at the laboratory, on the drug LSD, had actually come from a secret CIA program via two private foundations (see Witkowski, Road to Discovery, pp. 184-186). This was only revealed during congressional testimony in the early 1980s.
 
The institutional records from the earliest days of science at Cold Spring Harbor, when it was the site of a summer school in biology operated by the Brooklyn Institute of Arts and Sciences, are a spectacular source of information on how non-specialist participants in the sciences, such as secondary school teachers, managed to afford their training and continuing study in biology For example, it was common for summer students to earn their board by waiting tables at the Blackford Hall canteen, an arrangement known as a “waitship” (see CIW collection, box 25 and the BIAS collection).

**Comment by tomadams** [comment]
Looks complete.
