### ISSUE TITLE
Archives - Theme - Long Island history: relations between the lab and the community

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#54]
## Long Island history: relations between the lab and the community

description here.

### Relevant Collections
- Dr. Alan W. Bernheimer Sr. collection of Cold Spring Harbor Materials
- Brooklyn Institute of Arts and Sciences (1890-1941)
- Carnegie Institution of Washington at CSH administrative records (1898-1977) 
-- Administrative correspondence, 1898-1977
-- “Photographs, 1906-1959”
- CIW Eugenics Record Office collection
- CSH blueprints and maps collection (1855-2000)
- Cold Spring Harbor Laboratory collection (1923-) CSHL
- CSHL Office of Technology Transfer collection (1972-)
- Charles B. Davenport collection
-- Records related to property owned by Charles and Gertrude Davenport
-- Deeds and insurance information for other properties not owned by the Davenports
-- LIBA material
- Long Island Biological Association (1900-1962)
--  Property-transfer records
- Reginald G. Harris collection
- Bruce W. Stillman collection
- James D. Watson collection

**Comment by tomadams** [comment]
Captions for Long Island history: relations between the lab and the community 
1.	Original building of the CSH Fish Hatchery founded in 1881
2.	NY Senator Hillary Clinton at the Genome Center with Scott Lowe, ca. 2000s
3.	Bruce Stillman holds Citation by Nassau County Executive Ed Mangano for CSHL’s 125th Anniversary at the 2015 Open House
4.	Artist Bill Jonas at CSHL, 2015
5.	Bruce Stillman and Michael Dowling sign CSHL and North Well Health (previously NorthShore LIJ) affiliation, 2015

**Comment by srunkows** [comment]
Skeleton page created: https://lib-review-cshl-core.pantheonsite.io/archives/themes/long-island-history-relations-between-the-lab-and-the-community/

**Comment by tomadams** [comment]
### Long Island history: relations between the lab and the community
 
CSHL’s history is inextricably intertwined with the broader social, economic, and environmental histories of Long Island. As a result, the laboratory’s historical collections constitute a spectacular resource for investigating local and regional history, while simultaneously illuminating the degree to which the history of scientific research can and should be contextualized with information about the places and spaces where it occurred.
 
During experimental biology’s formative years in the late nineteenth century, the proximity to Long Island Sound made Cold Spring Harbor an excellent setting for a marine research station that would give new purpose to infrastructure built up around the whaling industry. Under the auspices of the Brooklyn Institute of Arts and Sciences (which also administered the Brooklyn Museum and the Brooklyn Academy of Music), and through the spirited work of several prominent Long Island families who were eager to cultivate science east of the boroughs of New York, the station quickly became a one of the nation’s premier training grounds for high-school and college biology teachers (many of them women who traveled to Cold Spring Harbor from around the country).
 
The facilities at Cold Spring Harbor proliferated into a year-round laboratory and field-research facility documenting the local environment and fostering discoveries in disciplines including crop science, animal genetics, and evolutionary biology, and, from 1910-1939, data-gathering in the now discredited field of eugenics. Even as the lab’s worldwide reputation expanded, its importance to the surrounding community, and vice versa, was confirmed when the Brooklyn Institute transferred its stake to the newly established Long Island Biological Association, again under the initiative of local patrons who were devoted to maintaining the island’s Gold Coast as a haven for science as well as high society.
 
These early decades are documented in the Brooklyn Institute of Arts and Sciences (BIAS) collection, the Long Island Biological Association (LIBA) collection, and the Carnegie Institution of Washington (CIW) collection, as well as the personal collections of two early directors of CSH institutions, Charles B. Davenport and Reginald G. Harris. Documents range from letters exchanged with the Long Island Railroad in 1920 about how to split the cost of inserting a LIRR map into circulars about the Bio Lab’s summer program (BIAS, box 1, folder 6) to property-transfer records showing how the laboratory grew within the communities of Cold Spring Harbor and Laurel Hollow (LIBA collection; C.B. Davenport collection). For an illustration of all that can be gleaned about local history from these institutional collections, see /Laboratory-community relations revealed in CSHL's Carnegie Institution collection/.
 
Along with equivalent institutional records in the CSHL collection and the personal collections of directors James D. Watson and Bruce Stillman, the intersections of lab life and town life in recent decades emerge vividly in many interviews in the Oral History collection. For example, Waclaw Szybalski describes evenings of high-society mingling with families in Lloyd’s Neck and Cold Spring Harbor in the 1950s, Jeffrey Miller recounts hints of tension between local law enforcement and countercultural impulses at the lab in the late 1960s, and Winship Herr recalls how a disagreement about property zoning for the laboratory helped to spur the creation of CSHL’s graduate school.
 
#### Related resources:
 
Watson, Elizabeth L. Grounds for Knowledge: A Guide to Cold Spring Harbor Laboratory’s Landscapes & Buildings. Cold Spring Harbor, NY: Cold Spring Harbor Laboratory Press, 2008.
 
Watson, Elizabeth L. Houses for Science: A Pictorial History of Cold Spring Harbor Laboratory. New York: Cold Spring Harbor Laboratory Press, 1991.
 
Witkowski, Jan A. The Road to Discovery: A Short History of Cold Spring Harbor Laboratory. Cold Spring Harbor, NY: Cold Spring Harbor Laboratory Press, 2016.

**Comment by tomadams** [comment]
Above text added to page.
