### ISSUE TITLE
Archives - Theme - Visual records and material culture

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#56]
## Visual records and material culture

description here.

### Relevant Collections
- Amos G. Avery photographic collection
- Sydney Brenner collection
-- Photographs
-- Drawing by Gamow
- Brooklyn Institute of Arts and Sciences (1890-1941)
- Elof Carlson collection
- Carnegie Institution of Washington at CSH administrative records (1898-1977) 
-- “Research photographs, 1935-1944”
-- “Photographs, 1906-1959”
- CIW Eugenics Record Office collection
- CSH blueprints and maps collection (1855-2000) BPM
- CSHL images collection (1921-) 
- Charles B. Davenport collection
-- Photographs
-- Drawings
-- Postcards
- Zoological drawings
- Hugo Fricke collection
-- Lantern slides depicting experimental results in graphical form
- Reginald G. Harris collection
-- Panama anthropological expedition
-- Cornell entomological expedition to South America
- Alfred Day Hershey collection
- Barbara McClintock collection
- Bruce W. Stillman collection
- Jeffrey Strathern collection
- Raquel Rotman Sussman collection
- Kitty Brehme Warren scrapbook collection
- James D. Watson collection
- Charles Weissmann Biogen collection
- Charles Yanofsky collection
- Norton Zinder collection
- Alfred Day Hershey collection (the blender)
- Reginald G. Harris collection (from expeditions)
- Roberto Malinow Laboratory collection (laboratory slides)
- Barbara McClintock collection (corn kernels; Groucho Marx mask)
- Herman J. Muller collection (feather used to mark Drosophila vials)

**Comment by tomadams** [comment]
Captions for Visual records and material culture
1.	Hugo Fricke First Full time investigator ca 1930s 
2.	Barbara McClintock’s maize, undated 
3.	Waring Blendor used in the Hershey-Chase Experiment, 1952
4.	Sydney Brenner’s laboratory notebook, 1961
5.	Carol Greider x-ray, ca. 1990s

**Comment by srunkows** [comment]
Skeleton page has been built: https://lib-review-cshl-core.pantheonsite.io/archives/themes/visual-records-and-material-culture/

**Comment by tomadams** [comment]
### Audiovisual Records and Material Culture

Our collection of audiovisual materials and material culture is the physical evidence of researchers human experience in their professional and personal lives. Through CSHL Archives’ records researchers’ can discover topics such as women in science, mentoring, and primary resources that highlight significant contributions to the life sciences. These materials cover the period of 1890 through the present time.

Since its inception the Center for Humanities at CSHL has taken over CSHL’s oral-history initiative and CSHL’s series of annual History of Science meetings, both of which are aimed at creating and preserving historical records to complement the material in our archives. History of science meeting series are distinctive in bringing participants who shaped a significant field of scientific research.  All talks are recorded. Transcripts of each talk and slides presented by speakers are available on the website.  These history of science meeting  websites present the unique resources documenting the intellectual and social history of the life sciences. 
	
CSHL Archives’ popular Oral History website (https://library.cshl.edu/oralhistory/ ) consists of first-person accounts recorded across the globe from 1990 to 2019 from over 200 scientists, including key figures in the molecular biology revolution and fifteen Nobel laureates. Due to their joint nature as interviews and free-flowing conversations, these recordings are some of the best first hand accounts of the day-today progress of the unfolding of modern biological research, medical biology, and major scientific endeavors such as the Human Genome Project, experiences of women in science, the character and life of leading scientists like Barbara McClintock, etc. The stories cover period from 1940s through the 2020.  These are keyword-tagged, transcription-text searchable, and also viewable in several curated thematic collections. 


The Institutional Collections (1890-present) contain photographs which depict the scientific and personal lives of staff, scientists, and visitors of The Biological Laboratory, Department of Genetics of the Carnegie Institution of Washington, Cold Spring Harbor Laboratory, Cold Spring Harbor Symposia, as well as meetings, courses, and events. Personal photographs from the Barbara McClintock Collection (1907-1992) depict her at Cornell University, Woods Hole Oceanographic Institute, Cold Spring Harbor Laboratory with colleagues, students, maize plants, and from events related to her being awarded the 1983 Nobel Prize. The James D. Watson Collection features photographs from 1928-2018 of his early life, discovery of the structure of DNA, manuscripts, colleagues and friends like Francis Crick, Matthew Meselson, George Gamow, and more. The Sydney Brenner Collection features photographs of Sydney Brenner from 1927-2000s of his childhood in South Africa, education at The University of Witwatersrand, as well as photographs of his wife May Brenner, children and stepson, additionally there are many portraits of Sydney Brenner and photographs of him presenting at and attending lectures and workshops. The Bruce Stillman Collection features photographs from the 1970s-2000s which include portraits, family photographs, and distinguished guests.  

Sydney Brenner and Carol Grieder’s laboratory notebooks which contains notes and drawings for their major discoveries (mRNA and telomerase) are historic primary resources for scholars, writers and teachers. Other visual records include pedigree charts (1908-1940) from the Eugenics Records Office Collection, as well as photographs of Eugenics Fieldworkers (1913-1935). Laboratory notebooks are another type of visual record found within the Carol Greider Collection, Bruce Stillman Collection, Sydney Brenner Collection, and Norton Zinder Collection.  X-ray films are included within the Carol Greider Collection, as well as within Norton Zinder Laboratory Notebooks. Alfred Hershey’s blender used in the famous Hershey-Chase experiments and Barbara McClintock’s dehydrated maize kernels are examples of some of the many additional primary materials found within our archives.

**Comment by tomadams** [comment]
Page is complete.
