### ISSUE TITLE
Archives - Sydney Brenner Research Fellowship  -Deadline change

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#57]
The application deadline needs to be updated, on the following page:
https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/grants-fellowships/sydney-brenner-research-fellowship-2/

### Please replace the following two sentences:
Applications are currently being accepted for the 2020–2021 academic year.

**Applications must be received by 11:59pm EST (UTC−05:00) on 31 January 2020 to be considered for the 2020-2021 academic year.**

with the single sentence:

**Applications must be received by 11:59pm EST (UTC−05:00) on 31 March 2021 to be considered for the 2021-2022 academic year.**

**Comment by srunkows** [comment]
This is done and ready for review.

**Comment by tomadams** [comment]
Great.
