### ISSUE TITLE
Archivies - BGI and Genetech

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#58]
On the "Guide to the CSHL Historical Collections" page, there are two square graphics links for BGI and Genentech collections. Those links go to these two pages, respectively. 

## BGI Nobel Laureates Archives

[BGI-Collections graphic floating to right] 
BGI Group, the global genomics leader headquartered in Shenzhen, China graciously gifted CSHL Archives $5 million in 2019. The gift establishes and preserves the BGI Nobel Laureates Archives [link to: https://cshl.edu/giving-news/bgi-nobel-laureates-archives-established-at-cold-spring-harbor-laboratory/], comprising all of the current and future personal collections of Nobel laureates held by the CSHL Archives.

The BGI Nobel Laureates Archives currently include Sydney Brenner, Francis Crick, Walter Gilbert, Carol Greider, Alfred Hershey, Barbara McClintock, Hermann Muller, Richard Roberts and James D. Watson.
      
[Photo BGI01.jpg]
 BGI Group’s Co-Founder and Chairman Huanming “Henry” Yang, CSHL’s President and CEO Bruce Stillman, and CSHL’s Executive Director of Library & Archives Ludmila Pollock. Photo Credit: Connie Brukin/2019

[Photo BGI02.jpg]
(back row): University of Cambridge’s Richard Durbin, CSHL President Bruce Stillman, Nobel laureate Walter Gilbert, University of Washington’s Robert Waterston, BGI’s Huanming “Henry” Yang, Yuqing Jiang, Charles Bao, and Damon Zhang. (front row): BGI’s Yongwei Zhang, CSHL’s Ludmila Pollock, and BGI’s Audrey Kong. Photo Credit: Connie Brukin/2019

#### BGI Collection
[Use the following photo/title boxes from the top-level Personal Collections page (but without the description), to link to each collection.]
- Sydney Brenner
- Francis H.C. Crick 
- Walter Gilbert 
- Carol Greider 
- Alfred Day Hershey 
- Barbara McClintock
- Hermann Muller
- Richard Roberts
- James D. Watson

## Genentech Center for the History of Molecular Biology and Biotechnology

[Genentech-Collections graphic floating to right] 
In honor of Genentech’s 30th anniversary in 2006, Genentech , the founder of the biotechnology industry, gifted $2.5 million dollars to Cold Spring Harbor Laboratory Archives to seed the establishment of the Genentech Center for the History of Molecular Biology and Biotechnology in CSHL's historic Carnegie Building, where genetics research began in the United States in 1904. [link to: https://cshl.edu/genentech-donates-25-million-to-cold-spring-harbor-laboratory/]

The Genentech Center for the History of Molecular Biology & Biotechnology  focuses on documenting the basic scientific research that underpinned the development of molecular biology and biotechnology. This research, carried out initially in academic laboratories, led to the development of recombinant DNA techniques, which in turn stimulated entrepreneurial scientists to create biotechnology companies.

The mission of the Genentech Center is to identify, acquire, preserve, promote, and provide centralized access to the original papers, correspondence, and research material materials of the individuals and institutions that were crucial to the development of molecular biology and biotechnology. The Center is also conducting oral history interviews. These materials are complemented with the images and voices of scientists who played a key role in the foundation of biotechnology.

[Photo Genentech01.jpg] 
Richard Scheller, exec VP, research at Genentech and James Watson, Arthur Levinson, chairman and CEO Genentech, 2006

#### Genentech Collection
[Use the following photo/title boxes from the top-level Personal Collections page (but without the description), to link to each collection.]
- Sydney Brenner
- Elof Carlson 
- Walter Gilbert 
- Herman J. Muller
- Bruce Wallace
- Charles Weissmann 
- Charles Yanofsky 
- Norton Zinder

**Comment by srunkows** [comment]
These pages have been created/updated.

BGI: https://lib-review-cshl-core.pantheonsite.io/archives/bgi-nobel-laureates-archives/
I do not have Photo BGI01.jpg and I'm not even sure there's enough content (text) on the page to lay in another photograph.
There is no personal collection page for Richard Roberts.

Genetech: https://lib-review-cshl-core.pantheonsite.io/archives/genentech/
I do not have Photo Genentech01.jpg

**Comment by tomadams** [comment]
Correct, there is not a Richard Roberts collection page, and there is unlikely to be one for quite some time. Emailed you the missing photos.

**Comment by tomadams** [comment]
For Genentech: https://lib-review-cshl-core.pantheonsite.io/archives/genentech/
- I did email you the Genentech01.jpg image on Mon 12/7/2020 3:18 PM, which should go on the Genentech page. 
- Please eliminate the Oral History section below.

For BGI:
Please eliminate the Richard Roberts card at the bottom. OK to keep his name in the text at the top.

**Comment by srunkows** [comment]
> For Genentech: https://lib-review-cshl-core.pantheonsite.io/archives/genentech/
> 
> * I did email you the Genentech01.jpg image on Mon 12/7/2020 3:18 PM, which should go on the Genentech page.
> * Please eliminate the Oral History section below.
> 
> For BGI:
> Please eliminate the Richard Roberts card at the bottom. OK to keep his name in the text at the top.

These updates are done.

**Comment by tomadams** [comment]
OK
