### ISSUE TITLE
Archives - The Guide end column

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#62]
With the exception of the "Archives Homepage" and the "Center for Humanities" pages, is it possible to add the "The Guide" text vertically, in the rightmost margin?

This would be in place of "The Guide" text appearing above the blue buttons in the right sidebar. Which you indicated was hard to do.

```
<div class="col-lg-1">
  <div style="writing-mode:tb-rl; font-size:80px;padding-left: 30px; color:lightsteelblue;" class="d-none d-sm-none">
    <a href="">The Guide</a></div>
</div>
```
Which would look something like this:
![image](https://user-images.githubusercontent.com/1951133/100936204-2b9c6600-34bf-11eb-8810-f2926abe36a9.png)

**Comment by srunkows** [comment]
No, I ran this idea past the Public Affairs design board and I'm sorry this is not a style we are willing to adopt for the website. I will add an additional field in the database to have a heading in the sidebar above the buttons.
