### ISSUE TITLE
DHP Acknowledgement Box

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#63]
On some of the collection pages is an acknowledgement box in the right hand column for the NYSED.gov DHP program. The text is a little off. Please use:

> This collection was processed under a 2011-2012 DHP award. Funding provided by the New York State Education Department's  Documentary Heritage Program. 

Please keep the existing NYSED.gov logo.

This box should appear in the following collection pages:
- Avery
- Barbara McClintock
- Hugo Fricke
- Brooklyn Institute of Arts and Sciences
- Carnegie Institution of Washington
- Cold Spring Harbor Laboratory
- Eugenics Record Office
- Long Island Biological Association

**Comment by srunkows** [comment]
> This box should appear in the following collection pages:
> 
> * Avery
> * Barbara McClintock
> * Hugo Fricke

These 3 pages have been updated.

I have not updated the Institutional Collections pages, since I have not received feedback on the layout of these pages yet and therefore do not know where to place this content yet.

**Comment by srunkows** [comment]
> * Brooklyn Institute of Arts and Sciences
> * Carnegie Institution of Washington
> * Cold Spring Harbor Laboratory
> * Eugenics Record Office
> * Long Island Biological Association

The box has been added to these pages

**Comment by tomadams** [comment]
Great.
