### ISSUE TITLE
Archives - Carnegie Institute of Washington / Patronage and Funding of Research (Collection/Theme connector)

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#64]
The following is a connector page explains how a particular collection is related to one of the historic themes. In this case between the Patronage and Funding theme with the CIW collection.

In cases where we do not have a connector page, the "Related Themes" (on a collections page) will link directly to a theme page, and the related collections (on a theme page) will link directly to a collection page.

However, when there is a connector page, such as the one below, both of the related theme and related collection will link to this connector page.

There will only be a minimal amount of pages of this type initially , but we should have the template in place for future content.

### Related Collections
Carnegie Institute of Washington (link to that collection)
### Related Themes
Patronage and Funding of Research (link to that theme)
### Related Resources
(none so this section will not appear

[Our normal group of The Guide and the Blue buttons]

### Patronage and Funding of Research & Carnegie Institute of Washington
	
The CIW collection provides insight into the relationship between the Carnegie Institute and Biological Laboratory and their patrons, especially on the local level. This topic shades into another, related, topic: Long Island history / relations between the lab and the community (see below).

What kind of information about patronage and funding does the CIW collection offer? The personal correspondence of important individuals at the lab reveals the work that was done to establish and maintain connections between the lab and its donors — wealthy men with no particular scientific backing were on the Managing Board of the Biological Laboratory, and a lot of effort was put into maintaining these relationships [CIW Box 39, Folder: Hooper, Franklin 1900-1902]. The lab also had to convince donors of the permanence and potential prestige of the institution [CIW Box 24, Folder: Davenport, Charles B. 1902-1905, Hooper to Charles Davenport, October 19, 1905] As Henry De Forest put it in 1923, “I do not care …to become connected with any new thing unless I regard it from my standpoint as something worthwhile.” He had no interest in “Biological School[s] of a lower grade” [CIW Box 26: Folder: De Forest, Henry W., 1923, De Forest to Davenport, Dec. 26, 1923]. The relationship between the De Forest family and the lab is worth a closer look. The surviving correspondence reveals a tension between, on the one hand, De Forest’s interest in being a patron and the prestige that came with that kind of work, and on the other, his and his friends’ personal financial interest in local property [CIW Box 26, Folder: De Forest, Henry W., 1923, Folder: De Forest, Julia, 1924-1928] As Davenport and other directors negotiated with men like De Forest, they had to articulate their own plans for the lab and the kind of institution it was and would become.

There is also the odd document (no more than one or two items) about the New Deal in the 1930s and private vs public funding for science. This appears in a folder with material relating to foundations and other sources of support [CIW Box 32, Folder: Foundations, 1921-1934].

**Comment by srunkows** [comment]
This page has been created and is redy for review: https://lib-review-cshl-core.pantheonsite.io/archives/patronage-and-funding-of-research-carnegie-institute-of-washington/

**Comment by tomadams** [comment]
great
