### ISSUE TITLE
Ellen Brenner Internship

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#66]
Please keep our existing  Ellen Brenner Memorial Scholarship page.
Create a new page named: Ellen Brenner Memorial Internship.

The content is at:
http://library.cshl.edu/grants/ellen-brenner-memorial-internship

Please also add a card for this page at:
https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/grants-fellowships/

**Comment by srunkows** [comment]
Done and ready for review:

https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/grants-fellowships/
https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/grants-fellowships/ellen-brenner-memorial-internship/

**Comment by tomadams** [comment]
Great.
