### ISSUE TITLE
Personal Collection- Wada

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#67]
Please replace the existing text in https://lib-review-cshl-core.pantheonsite.io/personal-collections/akiyoshi-wada/ with:

In 1981, Akiyoshi Wada led a national project in Japan to develop the world’s first automated DNA sequencing device. Dr. Wada was the first person in the world to propose automated high-speed technology for deciphering DNA sequence. By 1988, the Japanese Human Genome Project began as a response to the progress in the corresponding activities in the United States and Europe. The International Human Genome Project began under the cooperation of Japanese, European, and American researchers working on The International Human Genome Project. At a meeting in 1996 in Bermuda, a decision was taken to split the task of sequencing the human genome between several countries. Japan was allocated human chromosome 21, and the Japanese team, consisting of Yoshiyuki Sakaki, Nobuyoshi Shimizu, and their colleagues, successfully sequenced the entire chromosome in 2000 with the collaboration of the German team.

In Japan, the aim of the human genome project was redirected not only to sequence the genome but also to include functional analysis of genes and elucidation of tertiary protein structures. A successful approach in the Japanese human genome project is in placing emphasis on the promotion of functional genomics, comparative genomics, analysis of genomic diversity, and the development of DNA chips or microarrays.

Akiyoshi Wada is Professor Emeritus of Tokyo University, after having been a professor of Physics of the University and Director of the RIKEN Genomic Sciences Center (GSC), Yokohama, Japan. Currently, he is the Special Advisor of GSC, President of Yokohama Science Center, and Executive Director of Ochanomizu University. Wada studied biological macromolecules in Prof Paul Doty’s lab at Harvard University before joining the Department of Physics in the Faculty of Science at Tokyo University, where he studied the physical properties of DNA and proteins until 1990. In 1981, Wada led a national project in Japan to develop the world’s first automated DNA sequencing device. Wada was President of Biophysical Society of Japan (1974–1975), Council member of the International Union of Pure and Applied Biophysics (IUPAB) (1978–1984) and Director of Science Division of The Science Council of Japan (1997–2000). He was an instrumental architect of the Human Frontier Science Program (HFSP) in 1988.

This collection encompasses eight files and a binder of 24 CD-ROMs related to the completion of the human genome project. The files all relate to the Japanese human genome project including workshops, correspondence with Renato Dulbecco, reprints and photographs.

**Comment by srunkows** [comment]
This is done.

**Comment by tomadams** [comment]
Please add "The Guide" button above the rest of the blue buttons.

**Comment by srunkows** [comment]
> Please add "The Guide" button above the rest of the blue buttons.

Done.

**Comment by tomadams** [comment]
Thanks
