### ISSUE TITLE
Personal Collection - Husimi

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#68]
Please replace the existing text on https://lib-review-cshl-core.pantheonsite.io/personal-collections/dr-yuzuru-husimi/  with:

Dr. Yuzuru Husimi is currently Professor Emeritus at Saitama University and Professor of Functional Molecules at the Graduate School of Science and Engineering at Saitama University. He began his career at the University of Tokyo in 1969, and has also worked at Saitama University Faculty of Engineering; West German Max Planck biophysical RIKEN as a visiting fellow (1985); the Saitama Bio Project; and the Japan Science and Technology Agency. Dr. Husimi has published over 60 original papers on DNA and evolutionary molecular engineering. His recent major paper titles include: “Multi-line split DNA synthesis: a novel combinatorial method to make high quality peptide libraries.” BMC Biotechnol 2004 Sep 1; 4:. 19. Thermodynamical interpretation of an adaptive walk on a Mt. Fuji-type fitness landscape: Einstein relation-like formula holds in a stochastic evolution.” J Theor Biol 2003 Nov 21; 225 (2): 215-28. His specialty is in molecular biophysics; evolutionary molecular engineering; clarification of the principles of the emergence of functionality in fast molecular evolution as it is carried out in the laboratory and the actual creation of highly functional biological macromolecules; wetware artificial life; physics of the origin of biological information; and development of a fast DNA sequencer for the Human Genome Project.

In Japan, the aim of the human genome project was redirected not only to sequence the genome but also to include functional analysis of genes and elucidation of tertiary protein structures. A successful approach in the Japanese human genome project is in placing emphasis on the promotion of functional genomics, comparative genomics, analysis of genomic diversity, and the development of DNA chips or microarrays.

The International Human Genome Sequencing Consortium includes scientists at 16 institutions in France, Germany, Japan, China, Great Britain and the United States. Participants in the international consortium adhered to the project’s quality standards and to the daily data release policy. The project is funded by grants from government agencies and public charities in the various countries.

Dr. Husimi’s Collection contains reprints and patent applications related to his work on the Human Genome Project.

**Comment by srunkows** [comment]
This is done.

**Comment by tomadams** [comment]
Please add "The Guide" button above the rest of the blue buttons.

**Comment by srunkows** [comment]
> Please add "The Guide" button above the rest of the blue buttons.

Done.

**Comment by tomadams** [comment]
Good.
