### ISSUE TITLE
Personal Collection - Kambara

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#69]
Please replace the the text in https://lib-review-cshl-core.pantheonsite.io/personal-collections/dr-hideki-kambara/  with:

Dr. Hideki Kambara now is the Fellow of Hitachi Ltd., the visiting professor of three universities (University of Tokyo, Tokyo University of Agriculture and Technology, Tokyo Metropolitan Univ.). He graduated from the University of Tokyo in 1967, and received his doctorate degree in 1972 from the University of Tokyo. He started the development of DNA sequencers in 1982. He joined Akiyoshi Wada in 1984. He honored The Chemical Society of Japan Award for “Development of Capillary Array DNA sequencer for Genome Analysis” in 2009, The Asahi Prize for “Development of a high performance DNA sequencer” in 2004, the National Medal of Honor with Purple Ribbon in 2003, “Star of Asia” by BusinessWeek’s in 2002, the 48th Okochi Memorial Grand Technology Prize for “development of the capillary array DNA sequencer” in 2002, and Commendation by the Minister of Education, Culture, Sports, Science & Technology to Persons of Scientific & Technological Research Merits, for “Research on fluorescence detection method DNA base sequencing device” in 2001. Dr. Kambara has published over 90 original papers on mass spectrometry and DNA analysis, and holds more than 100 patents in Japan and U.S.A. His research interests includes atmospheric pressure ionization mass spectrometry; field desorption ionization and collision-induced decomposition mass spectrometer for biological molecules; molecular secondary ion mass spectrometry; combined system of liquid chromatograph and mass spectrometer; fluorescent DNA sequencer; capillary array DNA sequencer which was contributed greatly to the Human Genome Project; DNA expression profile analysis; and instruments for DNA diagnosis. Now he is interested in developing tools for analyzing mRNA in single cells.

In Japan, the aim of the human genome project was redirected not only to sequence the genome but also to include functional analysis of genes and elucidation of tertiary protein structures. A successful approach in the Japanese human genome project is in placing emphasis on the promotion of functional genomics, comparative genomics, analysis of genomic diversity, and the development of DNA chips or microarrays.

The International Human Genome Sequencing Consortium includes scientists at 16 institutions in France, Germany, Japan, China, Great Britain and the United States. Participants in the international consortium adhered to the project’s quality standards and to the daily data release policy. The project is funded by grants from government agencies and public charities in the various countries.

Dr. Kambara’s Collection contains eight notable reprints of his work and copies of eight patents directly related to his research.

### Sample of material within collection
![image](https://user-images.githubusercontent.com/1951133/101932172-6598f680-3ba8-11eb-8807-4ac5981a2115.png)
with the following caption:
illustration of Kambara patent diagram
The use of Capillary or Tube Gel Array for DNA Sequencing. Japanese patent and US Patent 4830830 [Apparatus for Determining Base Sequence of Nucleic Acid] [Photocopy] 1989

**Comment by srunkows** [comment]
This is done.

**Comment by tomadams** [comment]
Please add "The Guide" button above the rest of the blue buttons.

**Comment by srunkows** [comment]
> Please add "The Guide" button above the rest of the blue buttons.

Done

**Comment by tomadams** [comment]
OK
