### ISSUE TITLE
Institutional Collections - HGP Japan

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#70]
Please remove the page: https://lib-review-cshl-core.pantheonsite.io/archives/human-genome-project-japan/

That institutional collection has been replaced by three individual Personal Collection pages.

It's link on the: https://lib-review-cshl-core.pantheonsite.io/archives/institutional-collections/ page, should also be removed.

**Comment by srunkows** [comment]
This is done.

**Comment by tomadams** [comment]
OK
