### ISSUE TITLE
Advisory Board

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#75]
On page: https://lib-review-cshl-core.pantheonsite.io/archives/about/advisory-board/
Please remove:
Waclaw Szybalski, Professor Emeritus, McArdle Laboratory for Cancer Research
University of Wisconsin-Madison

Please update:
Charles Weissmann, Professor Emeritus, Department of Immunology and Microbiology
Scripps, Florida Campus

**Comment by srunkows** [comment]
Done and ready for review.

**Comment by tomadams** [comment]
Thanks
