### ISSUE TITLE
Library - OVID

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#76]
In 2021, we are no longer subscribing to OVID. Please remove the reference to that database.

Page:  https://lib-review-cshl-core.pantheonsite.io/library/resources/databases-protocols/
Ovid from Wolters Kluwer Health

Page:  https://lib-review-cshl-core.pantheonsite.io/library/services/sfx-find-it/
OVID
    Biosis
    HealthSTAR/Ovid Healthstar
    MEDLINE

**Comment by srunkows** [comment]
This is done.

**Comment by tomadams** [comment]
Great.
