### ISSUE TITLE
Archives - Connector CIW and LI History Theme

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#77]
Use the same template as: https://lib-review-cshl-core.pantheonsite.io/archives/patronage-and-funding-of-research-carnegie-institute-of-washington/

On the right hand column, please link to the two pages:
### Related Collections
Carnegie Institute of Washington ==> https://lib-review-cshl-core.pantheonsite.io/archives/institutional-collections/carnegie-institution-of-washington/

### Related Themes
Long Island history: Relations between the lab and the community ==> https://lib-review-cshl-core.pantheonsite.io/archives/themes/long-island-history-relations-between-the-lab-and-the-community/

**NOTE1:** On the two above pages, there will also need to be a link back to this connector page. On the CIW page the link should be listed under "Related Themes". On the "LI History: Relations..." theme page, the link should be listed under "Related Collections". For example the return link should be below the CIW Collection inventory and above the blue "The Guide..." button.

**NOTE2:** Note that on the connector page: https://lib-review-cshl-core.pantheonsite.io/archives/patronage-and-funding-of-research-carnegie-institute-of-washington/ also needs to have similar back links on both the CIW Collection and Patronage Theme pages.

## CIW & LI history: relations between the lab and the community
 
From the beginning, it was clear that good relationships with the local community would be important for the success of the Biological Laboratory and the Station for Experimental Evolution. The correspondence in Davenport’s papers contains discussion of this topic. For example, Franklin W. Hooper of the Brooklyn Institute wrote to William J. Matheson in July of 1902 that the “the Laboratory should be managed as to command the support of the residents of Cold Spring Harbor, who are naturally friendly to the Laboratory and who will be glad to see a first class Research Station in Biology conducted there” [CIW Box 24, Folder: Davenport, Charles B. 1902-1905, July 5, 1902]. The number of students at the growing institution was a matter of concern for some of the wealthy landowners — among them donors or potential donors — who lived nearby. Davenport met with two of them personally in order to assuage their concerns about the future Station for Experimental Evolution [CIW Box 24, Folder: Folder: Davenport, Charles B. 1902-1905, July 9, 1902].
          
  The Carnegie Institution Collection also reveals the smaller, day-to-day problems that arose between the lab and its neighbors. Hooper categorized complaints from the Tiffany and De Forest families in the early 1900s about the number of students and the students going to and from the beach in their bathing suits, as “trivial.” It seemed to him that the point of these complaints was to reinforce the idea that these families had “exclusive right-of-way over the road-way leading down to the beach” [CIW Box 39, Folder: Hooper, Franklin 1900-1902, July 20, 1902]. The collection also has other references to the minor problems caused by the presence of the students — noise, minor property damage, etc. [CIW Box 24, Folder: Davenport, Charles B. 1902-1905, Joshua Jones to Davenport, July 17, 1902; there are numerous references to this sort of thing throughout Davenport’s correspondence, CIW Boxes 24-25, and in the correspondence of other directors of the Bio Lab and Carnegie Institution lab.] See also an exchange of letters in 1938 between the rector of St. John’s Church and Eric Ponder. The students had been given tacit permission to swim in a pond near the church, but their presence was attracting “many of the people we don’t want,” according to the rector. These individuals assumed that the pond was open to the public and the rector said that their presence was a nuisance. [CIW Box 12, Folder: Buildings and Grounds, 1893-1962, Bleecker to Ponder, June 14, 1938.]
          
  As trivial as these complaints might have been, the lab could not afford to offend neighbors like the Tiffanys or Henry De Forest [see above, Patronage]. Often, they had to tread extremely carefully — when the lab was interested in purchasing additional land early in the twentieth century, they had to take into account the interests of other potential purchasers in the neighborhood, who might also be potential donors. They had to avoid offending them or coming into direct conflict with them, which was often tricky in such a small town [CIW Box 39, Folder: Hooper, Franklin 1900-1902, about a potential land purchase in 1902]. In addition, wealthy neighbors could be a potential source of financial support for students. In 1909, for example, an incoming student was advised that if he needed to earn money to support his summer work, there were often odd jobs to be had from “wealthy residents of Long Island” [CIW Box 40, Folder: J  Miscellaneous, letter to Harry M. Jennison, June 21, 1909].
         
The beach was a long-running source of conflict. Property lines, rights of way, and the complex ownership relations of the little spit of sand at the far end of the campus. The Carnegie Institution had a 1/18 undivided interest in the sand spit, which meant that people affiliated with the lab had the right to use the entire beach, but they  had to share this right with the various owners who owned the fractions that made up the other 17/18. This led to politely expressed but difficult to resolve conflicts between the lab and Henry De Forest, whose land was right next door. De Forest wanted the students to respect his property: staying on the path to the beach and off the grass, not making noise, wearing something over their bathing suits when they went down to go swimming. The beach, however, was and is a key part of the collegial aspect of the lab. Lab directors were aware that beach access was a draw for potential summer students and researchers (it remains a factor in Cold Spring Harbor’s attractiveness as a location for scientific meetings).
          
By the 1930s, the directors of the Biological Laboratory and the Carnegie Department of Genetics (formerly the Station for Experimental Evolution) and the De Forests had worked out a system for regulating the use of the beach — numbered beach passes would be given out each summer and a list would be kept of who had which number in order to prevent unauthorized access. A guard was posted to prevent outsiders from using the beach. This system created headaches for everyone involved, since it involved a lot of administrative work and a certain amount of policing.
         
This conflict and its resolution are significant for a number of reasons. First, the question of who was considered “worthy” of a beach card raised the issue of who was member of the lab community. In 1935, for example, Blakeslee raised the question with Davenport of whether non-scientific workers were to have access to the beach [CIW Box 6, Folder: Beach Cards - Sandspit 1935-1954, Blakeslee to Davenport, June 29, 1935]. Second, there were the related issues of race and social class. De Forest did not want beach cards to be given out to what he called “the colored help,” that is, the lab’s black dormitory and dining hall workers; he was also expressed concern from time to time that, in general, too many of what he considered the wrong sort of people of whatever color were using the beach [CIW Box 6, Folder: Beach Cards - Sandspit 1935-1954, correspondence between Davenport and Blakeslee, June-July 1935].
      
The question of how to prevent outsiders from using the beach persisted into the 1940s, even after Julia de Forest left her family’s interest in the sandspit to the lab (even after that, there were still some questions about the ownership of the beach) [CIW Box 25, Folder: Davenport, Charles B. 1942-1966, Demerec to Vannevar Bush, May 20, 1942]. Paying for a guard to prevent unauthorized access was expensive, and in the late 1940s the lab collaborated with the village of Laurel Hollow to create a subscription service: people affiliated with the lab and residents of the village of Laurel Hollow could pay for a pass, with the fees covering the cost of the guard [CIW Box 6, Folder: Beach Cards - Sandspit 1935-1954, Notices re: beach access, June 5, 1946 and June 14, 1947].
       
The conflict about the beach at Cold Spring Harbor Lab is also connected to a wider issue about public access to beaches on Long Island. Property owners want to claim the shore as private property or restrict access to local residents only, even in areas where federal funding has been used to maintain or improve the beach; the general public wants access to the beaches. The solution that the lab and the village of Laurel Hollow arrived at in the 40s places them in the category of those wanting to limit public beach access. However, the lab had long been aware of the need for public beach access. Blakeslee discussed this with the supervisor of the town of Huntington in 1932, revealing himself to be sympathetic to the position of those who lacked access to public beaches [CIW Box 6, Folder: Beaches 1932-1954, Blakeslee correspondence with town of Huntington, 2 August, 1932]. To step back even further, the controversy over the beach reveals a connection between the story of CSHL and a persistent theme in the history of Long Island: the desire of many locals, whether wealthy villa-owners or ordinary local people, to keep outsiders out.
       
For material relating to use of the beach, see: CIW Box 24, Folders: Davenport, Charles Benedict, 1912-1917, Davenport, Charles Benedict, 1908-1910; CIW Box 25, passim; most of the info is CIW Box 6, Folder: Beach Cards - Sandspit 1935-1954, Folder: Beaches 1932-1954.
     
Other material in the CIW collection relating to local history and the lab’s relations with the surrounding communities can be grouped under three main headings.
     
First, there is material relating to scientific and/or pedagogical collaboration with local schools, hospitals, clubs etc. Relations with the Huntington Hospital were very cordial, up to and including invitations to clam bakes [CIW Box 39, Folder: Huntington Hospital, 1937-1946]. Visitors to the lab took the opportunity to give talks on topics not directly related to science, e.g. in 1952, a visiting scholar from South Africa gave a presentation to “our neighborhood group” about his country [CIW Box 27, Folder: Demerec, Milislav, 1952-1958, Feb. 25-April 30, 1952]. The lab allowed local groups to use the auditorium, but tried to avoid groups that might seem partisan, or groups attempting to use the space to earn money [CIW Box 65, Folder: Visitors, 1963, 1964, 1967, memo dated June 21, 1963]. There is a lot of correspondence from the 1940s dealing with visits by groups of students from local high schools. The lab was doing scientific outreach/education based on studying Drosophila, and the list of school groups includes a Drosophila club from a Bronx high school in April of 1948 [CIW Box 26, Folder: Demerec, Milislav, 1947; CIW Box 27, Folder: Folder: Demerec, Milislav 1940-1941, Folder: Demerec, Milislav, 1946, Folder: Demerec, Milislav, 1948]. By the mid-1950s, the Biological Laboratory had been running a summer nature study course for young people for some time [CIW Box 27, Folder: Demerec, Milislav, 1952-1958, Demerec to Margaret V. Wall, March 7, 1955].
    
The Carnegie Institution collection also includes information on local problems and administrative and environmental issues that were of interest to everyone who lived or owned property in the area. For example, the controversy in the 1950s over whether and how the harbor should be dredged sheds light on the lab’s role as local landowner and its involvement in questions of environmental protection, conservation, infrastructure improvements, etc. [CIW Box 6, Folder: Beaches 1932-1954]. There is also material on the potential widening of 25A / traffic safety [CIW Box 38, Folder: Highway - widening 25A, 1934-1937], a local collaboration to remove yachters’ trash from the harbor [CIW Box 22, Folder: Misc. Correspondence 1909-1956, letter from W. A. W. Stewart Jr., chair of the Cold Spring Harbor Village Improvement Society, to the Carnegie Institution at CSH, June 30, 1937], and other issues like snow removal, traffic and zoning, dogs running loose, etc. [CIW Box 41, Folder: Laurel Hollow, 1957[9?]-1974]. This material contains a number of documents that highlight the question of the lab’s relationship to the local community, e.g. in late November of 1962, there was a discussion about whether the lab should give the local police a Christmas gift — the participants noted that the lab did not pay local taxes, but did sometime use the police [CIW Box 41, Folder: Laurel Hollow, 1957[9?]-1974].
        
Finally, there is material relating to the position or role of the lab in the community that raises the question of what kind of an institution the lab was and what its mission ought to be. The best example of this is the significant amount of archival material dealing with where to put the local whaling museum. Early in its history, Cold Spring Harbor had been a whaling town, and there were a number of local people interested in creating a whaling museum. Davenport was in favor of the idea — one of the key pieces in the prospective museum was to be a whaleboat (a small boat, not a ship) that Davenport had gotten from someone he knew at the American Museum of National History and which was initially stored in the garage of Mrs. Robert De Forest, the grandmother of the chairman of the local Village Improvement Society [CIW Box 25, Folder: Davenport, Charles B., 1935-1937, Davenport to Blakeslee, December 2, 1937]. The core of the issue was the location. Should the museum be built near the village green at the center of town, which for a lot of people seemed the more logical choice, or should it be built on a piece of the lab’s property known as the “factory property”? This piece of property was of uncertain ownership — as in the case of the sandspit, the right to use it was divided among a number of different owners. One of these was the Wawepex Society, which was in favor of the museum being built there. Davenport was a very enthusiastic proponent of the idea, because if built on the lab’s grounds, the museum could include an exhibition space for the Biological Laboratory and/or the Department of Genetics. In Davenport’s view, “such a wing would serve to bring the work of the Department into closer touch with the community” [CIW Box 25, Folder: Davenport, Charles B., 1938-1941, Davenport to Blakeslee, March 12, 1938; CIW Box 66, Folder: Folder: Wawepex C.I.W. 1892-2008, unknown to George L. Streeter, Sept. 16, 1938 (letter is in the folder marked 1936). Davenport spoke of exhibition space for the Department of Genetics, but Streeter’s correspondent assumed it was for LIBA]. However, the staff at the lab “unanimously” agreed that the museum did not belong on campus [CIW Box 47, Folder: Notices and Memoranda 1935-1964] and the matter was said to be giving “the Washington office….a headache” [CIW Box 25, Folder: Davenport, Charles B., 1938-1941, Streeter to Blakeslee, Feb. 7, 1938]. The discussion of the museum’s location brought up all kinds of questions about what the lab’s public role should be and whether it would be a good idea (or even safe, given the then very dangerous intersection of Bungtown Rd. and 25A) to have large numbers of outside visitors on campus. Material on the whaling museum can be found in CIW Box 25, Folder: Davenport, Charles B., 1935-1937, Folder: Davenport, Charles B., 1938-1941; CIW Box 66, Folder: Wawepex Society, 1926-1951, Folder: Wawepex C.I.W. 1892-2008, Folder: Wawepex Society [undated].

**Comment by srunkows** [comment]
Let's save this for our training session. This is perfect for walking you through how to set up a new page and add content.

**Comment by tomadams** [comment]
Added this connector.

Still need to address NOTE #2.

**Comment by tomadams** [comment]
Updated Patronage links, as per Note #2.
