### ISSUE TITLE
Library Homepage - Right Side Links

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#8]
BLUE BUTTONS

> Resources
> Services
> Faculty Profiles       https://facultyprofiles.cshl.edu/

Library QuickLinks

> Journals
> Library Catalog
> Databases & Protocols
> Institutional Repository
> Contact Us

LibGuides

> Bibliometrics
> Browzine
> Data Management          https://cshl.libguides.com/datamanagementCSHL
> Public Access Compliance   https://cshl.libguides.com/NIH_Compliance
>  ......See all LibGuides

Archives & Humanities

> CSHL Archives
> Center for Humanities
> History of Science Meetings

Note: merge Database and Protocols pages together.  Under discussion with Mila
eResources
Get Articles & Books
Training, Classes & Reference
Citation Tools

**Comment by srunkows** [comment]
All the content/links in the right side bar have been updated to reflect the provided list. Merging the database & protocols pages together needs clarification on how you want the content to be laid out on the page. Also note, neither page as they currently exist has an summary paragraph of what the content on the pages are and therefore only the page title will be returned in the website search results without a summary paragraph.

**Comment by tomadams** [comment]
Address the merging of the database and protocols page separately.
