### ISSUE TITLE
Library Homepage - Notices and Announcements

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#9]
Currently there is static text under the search box. That text should be removed (about the library page should handle this description.)
This area should be used for notices and announcements, in a blog type format. Each article should have a pictures displayed  if one exists.

**Comment by srunkows** [comment]
Each landing page on the core website requires a summary paragraph, typically a mission statement. This is required for several reasons, SEO, ADA, search results.

I shortened the content by removing the paragraph about the Archives, and leaving the paragraph about the Library.

Yesterday we spoke about having a news feed on the landing page. Is this in addition to notices and announcements or in place of notices and announcements? Before I start writing any code we need to discuss exactly what content you want displayed: news, announcements, events, etc.

**Comment by tomadams** [comment]
In the existing joomla site, I am not making the distinction between: articles, news, announcements, events, notices and content. Just as the long as the content is in on or two places in the hierarchy, with the highlight flag on, it appears on the home page. If there is a distinction between all of those items on the integrated site, I would need to understand what it is, to be able to answer your question.

**Comment by srunkows** [comment]
Yeah, we will need to discuss this further. News has a different post type than events and we typically don't keep announcements as post types. That info would normally just call into a callout box.

Let's carve out some time for a zoom call, maybe Friday, so I can explain the different Wordpress post types and we can brainstorm the best approach to displaying the info on your landing page.

**Comment by tomadams** [comment]
Sent ZOOM invite for today at 10AM

**Comment by tomadams** [comment]
Looking forward to seeing what you are able to come up with for the articles/news/announcements on the Library home page. Is there anything you need from me?

**Comment by srunkows** [comment]
Don't need anything at the moment. I started working on it and I think I have a solution, which I have been implementing. I'm hoping I can get some quiet time this week to make alot of progress so I can show you an example by the end of the week.

**Comment by srunkows** [comment]
Sorry for the delay. I just finished coding the solution for the feed on the Library landing page. I need to do testing and will push it out to production and the lib-review branch. It should be ready for your review right after the Labor Day weekend.

**Comment by srunkows** [comment]
The feed for the Library landing page has been implemented.  https://lib-review-cshl-core.pantheonsite.io/library/

After choosing the content you can order it in any way with a drag and drop interface in the back end.

In the interest of time, I included only the first 3 announcements that are currently on the library.cshl.edu website.

**Comment by tomadams** [comment]
Looks good. Should have been closed 20 days ago.
